import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'hi' ? 'hi' : 'en') as Language;
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.learnMore': 'Learn More',
    'common.getQuote': 'Get Free Quote',
    'common.readMore': 'Read More',
    'common.contactUs': 'Contact Us',
    'common.apply': 'Apply Now',
    
    // Navbar
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.allServices': 'All Services',
    'nav.allServicesDesc': 'Comprehensive solar solutions',
    'nav.residential': 'Residential Solar',
    'nav.residentialDesc': 'Rooftop solutions for homes',
    'nav.commercial': 'Commercial Solar',
    'nav.commercialDesc': 'Large-scale business solutions',
    'nav.maintenance': 'Maintenance & Support',
    'nav.maintenanceDesc': '24/7 monitoring and cleaning',
    'nav.resources': 'Resources',
    'nav.financing': 'Financing Options',
    'nav.financingDesc': 'Easy EMI and loan schemes',
    'nav.pmSubsidy': 'PM Solar Subsidy',
    'nav.pmSubsidyDesc': 'Government schemes & benefits',
    'nav.products': 'Products',
    'nav.productsDesc': 'High-performance solar panels',
    'nav.calculator': 'Solar Calculator',
    'nav.calculatorDesc': 'Calculate your savings',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.getQuote': 'Get Free Quote',

    // Footer
    'footer.company': 'ATP Infratech',
    'footer.description': 'Leading solar solutions provider in India. Empowering homes and businesses with clean, sustainable energy.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.solarConsultation': 'Solar Consultation',
    'footer.contactUs': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // Services Page Features
    'services.residential.feature1': 'Custom design for your rooftop',
    'services.residential.feature2': 'High-efficiency solar panels',
    'services.residential.feature3': '25-year performance warranty',
    'services.residential.feature4': 'Net metering setup included',
    'services.residential.feature5': 'PM Subsidy assistance',
    'services.commercial.feature1': 'Large-scale installations',
    'services.commercial.feature2': 'Energy audit & optimization',
    'services.commercial.feature3': 'Quick ROI (3-5 years)',
    'services.commercial.feature4': 'Tax benefits & depreciation',
    'services.commercial.feature5': 'Power purchase agreements',
    'services.maintenance.feature1': '24/7 monitoring system',
    'services.maintenance.feature2': 'Regular cleaning & inspection',
    'services.maintenance.feature3': 'Performance optimization',
    'services.maintenance.feature4': 'Rapid breakdown support',
    'services.maintenance.feature5': 'Extended warranty options',

    // Home Page
    'home.hero.title': 'Power Your Future with',
    'home.hero.titleHighlight': 'Clean Solar Energy',
    'home.hero.subtitle': 'Save up to 90% on electricity bills. Get government subsidy up to ₹108,000. Join 10,000+ happy customers across India.',
    'home.hero.cta1': 'Get Free Consultation',
    'home.hero.cta2': 'Calculate Savings',
    
    'home.whyChoose.title': 'Why Choose Solar Energy?',
    'home.whyChoose.subtitle': 'Multiple benefits that make solar the smartest investment',
    'home.whyChoose.saveMoney': 'Save Money',
    'home.whyChoose.saveMoneyDesc': 'Cut electricity bills by 70-90%',
    'home.whyChoose.govSubsidy': 'Government Subsidy',
    'home.whyChoose.govSubsidyDesc': 'Get up to ₹108,000 subsidy',
    'home.whyChoose.ecoFriendly': 'Eco-Friendly',
    'home.whyChoose.ecoFriendlyDesc': 'Zero emissions, clean energy',
    'home.whyChoose.increaseValue': 'Increase Property Value',
    'home.whyChoose.increaseValueDesc': 'Boost home value by 3-4%',

    'home.solutions.title': 'Complete Solar Solutions',
    'home.solutions.residential': 'Residential Solar',
    'home.solutions.residentialDesc': 'Perfect for homes and apartments. Save ₹30,000+ annually on electricity bills.',
    'home.solutions.commercial': 'Commercial Solar',
    'home.solutions.commercialDesc': 'Ideal for businesses and industries. Reduce operational costs by 80%.',
    'home.solutions.maintenance': 'Maintenance & Support',
    'home.solutions.maintenanceDesc': '24/7 monitoring and maintenance. Keep your system running at peak performance.',
    'home.solutions.learnMore': 'Learn More',

    'home.subsidy.badge': 'Government Initiative',
    'home.subsidy.title': 'Get Up to ₹108,000',
    'home.subsidy.titleHighlight': 'PM Solar Subsidy',
    'home.subsidy.desc': 'The Government of India offers substantial subsidies for residential rooftop solar installations. Get 60% subsidy on system cost.',
    'home.subsidy.point1': '₹60,000 subsidy for 1 kW system',
    'home.subsidy.point2': '₹90,000 subsidy for 2-3 kW system',
    'home.subsidy.point3': '₹1,08,000 subsidy for 3+ kW system',
    'home.subsidy.cta': 'Check Your Eligibility',

    'home.testimonials.title': 'What Our Customers Say',
    'home.testimonials.subtitle': 'Join thousands of satisfied solar users across India',

    // Testimonials
    'testimonial.1.name': 'Rajesh Kumar',
    'testimonial.1.location': 'Lucknow, Uttar Pradesh',
    'testimonial.1.text': 'ATP Infratech installed a 5kW system on my rooftop. With the PM subsidy, I only paid 60% of the cost. My electricity bill dropped from ₹8,000 to ₹800!',
    'testimonial.1.savings': '90% bill reduction',
    'testimonial.2.name': 'Priya Sharma',
    'testimonial.2.location': 'Noida, Uttar Pradesh',
    'testimonial.2.text': 'The financing option made solar affordable for us. Easy EMI and excellent customer support throughout the installation process.',
    'testimonial.2.savings': 'Zero down payment',
    'testimonial.3.name': 'Amit Patel',
    'testimonial.3.location': 'Varanasi, Uttar Pradesh',
    'testimonial.3.text': 'Commercial installation completed in just 2 weeks. Professional team and high-quality panels. ROI achieved in 3.5 years!',
    'testimonial.3.savings': '3.5 year payback',
    'testimonial.4.name': 'Sunita Verma',
    'testimonial.4.location': 'Kanpur, Uttar Pradesh',
    'testimonial.4.text': 'Maintenance service is outstanding. Regular cleaning and monitoring ensure maximum efficiency. Great investment for the future!',
    'testimonial.4.savings': '24/7 monitoring',
    'testimonial.5.name': 'Vikram Singh',
    'testimonial.5.location': 'Agra, Uttar Pradesh',
    'testimonial.5.text': 'Best decision for my home! The hybrid inverter system works perfectly even during power cuts. Now I have 24/7 electricity backup.',
    'testimonial.5.savings': 'Complete backup',
    'testimonial.6.name': 'Meera Gupta',
    'testimonial.6.location': 'Ghaziabad, Uttar Pradesh',
    'testimonial.6.text': 'Excellent service from start to finish. The smart monitoring app helps me track my savings daily. Highly recommended!',
    'testimonial.6.savings': 'Smart monitoring',

    'home.cta.title': 'Ready to Go Solar?',
    'home.cta.subtitle': 'Get a free consultation and start saving on electricity bills today',
    'home.cta.button': 'Get Free Quote Now',

    // About Page
    'about.hero.badge': 'Leading Solar Innovation Since 2023',
    'about.hero.title': "Powering India's",
    'about.hero.titleHighlight': 'Clean Energy',
    'about.hero.titleEnd': 'Future',
    'about.hero.subtitle': 'ATP Infratech is at the forefront of solar revolution in India, delivering sustainable energy solutions that transform lives and businesses.',
    'about.hero.cta1': 'Partner With Us',
    'about.hero.cta2': 'Explore Services',

    // Contact Page
    'contact.hero.badge': "Let's Connect",
    'contact.hero.title': 'Get Your',
    'contact.hero.titleHighlight': 'Free Solar Quote',
    'contact.hero.subtitle': 'Ready to go solar? Our experts are here to help you every step of the way. Get personalized consultation today.',
    'contact.form.title': 'Send us a message',
    'contact.form.subtitle': "Fill out the form and we'll get back to you within 24 hours",
    'contact.form.name': 'Full Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.email': 'Email Address',
    'contact.form.service': 'Service Interest',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Inquiry',
    'contact.form.privacy': 'By submitting this form, you agree to our privacy policy and terms of service.',
    'contact.confirmation.title': 'Thank You!',
    'contact.confirmation.message': 'Your inquiry has been submitted successfully. Our team will contact you within 24 hours to discuss your solar requirements.',
    'contact.confirmation.button': 'Close',
    
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Office Address',
    'contact.info.phone': 'Phone Numbers',
    'contact.info.email': 'Email Us',
    'contact.info.hours': 'Business Hours',
    'contact.info.hoursValue': 'Monday - Saturday: 9:00 AM - 6:00 PM\nSunday: By Appointment Only',

    'contact.experts.title': 'Talk to Our Experts',
    'contact.experts.subtitle': 'Get personalized solar solutions from our certified team',
    'contact.why.title': 'Why Choose ATP Infratech?',
    'contact.why.point1': '8+ years of solar excellence',
    'contact.why.point2': '10,000+ happy customers',
    'contact.why.point3': 'ISO certified installations',
    'contact.why.point4': '25-year performance warranty',
    'contact.why.point5': '24/7 customer support',

    // Services Page
    'services.hero.badge': 'Comprehensive Solar Services',
    'services.hero.title': 'Solar Solutions for',
    'services.hero.titleHighlight': 'Every Need',
    'services.hero.subtitle': 'From residential rooftops to large commercial installations, we provide end-to-end solar solutions tailored to your requirements',
    'services.residential.title': 'Residential Solar Solutions',
    'services.residential.desc': 'Transform your home into a clean energy powerhouse with our customized rooftop solar systems',
    'services.commercial.title': 'Commercial & Industrial Solar',
    'services.commercial.desc': 'Scale your business with cost-effective solar solutions that reduce operational expenses',
    'services.maintenance.title': 'Maintenance & Support',
    'services.maintenance.desc': 'Keep your solar system running at peak performance with our comprehensive maintenance services',
    'services.process.title': 'Our Installation Process',
    'services.process.subtitle': 'Simple, transparent, and hassle-free',
    'services.process.step1': 'Consultation',
    'services.process.step1.desc': 'Free site assessment and system design',
    'services.process.step2': 'Planning',
    'services.process.step2.desc': 'Financing, permits, and approvals',
    'services.process.step3': 'Installation',
    'services.process.step3.desc': 'Professional installation by certified team',
    'services.process.step4': 'Support',
    'services.process.step4.desc': 'Monitoring, maintenance, and ongoing support',
    'services.cta.title': 'Start Your Solar Journey Today',
    'services.cta.subtitle': 'Get a free consultation and custom solar solution for your needs',

    // Residential Service
    'residential.hero.title': 'Power Your Home with',
    'residential.hero.titleHighlight': 'Clean Energy',
    'residential.hero.subtitle': 'Save up to 90% on electricity bills with our premium rooftop solar systems. Get up to 60% government subsidy on installation costs.',
    'residential.hero.cta1': 'Get Free Assessment',
    'residential.hero.cta2': 'Check Subsidy',
    'residential.benefits.title': 'Why Go Solar for Your Home?',
    'residential.benefits.subtitle': 'Multiple benefits that make solar the smart choice for your home',
    'residential.benefits.benefit1.title': 'Save Money',
    'residential.benefits.benefit1.desc': 'Reduce electricity bills by up to 90%',
    'residential.benefits.benefit2.title': 'Clean Energy',
    'residential.benefits.benefit2.desc': 'Zero emissions, 100% renewable power',
    'residential.benefits.benefit3.title': '25-Year Warranty',
    'residential.benefits.benefit3.desc': 'Long-term performance guarantee',
    'residential.benefits.benefit4.title': 'Energy Independence',
    'residential.benefits.benefit4.desc': 'Generate your own electricity',
    'residential.components.title': 'Complete Solar System Components',
    'residential.components.subtitle': 'Our residential solar systems include everything you need for clean, reliable power generation',
    'residential.components.panel.title': 'High-Efficiency Solar Panels',
    'residential.components.panel.desc': 'Monocrystalline, Polycrystalline and Thin Film panels with 21%+ efficiency',
    'residential.components.inverter.title': 'Smart/Hybrid Inverter',
    'residential.components.inverter.desc': 'Advanced power management with battery backup capability',
    'residential.components.monitoring.title': 'Monitoring System',
    'residential.components.monitoring.desc': 'Real-time tracking through mobile app',
    'residential.components.structure.title': 'IIT Approved Structures',
    'residential.components.structure.desc': 'Hot/Cold galvanized stable mounting structures',
    'residential.components.subsidy.title': 'Government Subsidy',
    'residential.components.subsidy.desc': 'Get up to ₹1,08,000 government subsidy',
    'residential.pricing.title': 'System Sizes & Investment',
    'residential.pricing.subtitle': 'Choose the right system for your home and budget',
    'residential.pricing.ongrid': 'On-Grid Solar Systems',
    'residential.pricing.hybrid': 'Hybrid Solar Systems (With Battery Backup)',
    'residential.pricing.systemSize': 'System Size',
    'residential.pricing.suitable': 'Suitable for:',
    'residential.pricing.generation': 'Generation:',
    'residential.pricing.investment': 'Investment:',
    'residential.pricing.subsidy': 'PM Subsidy:',
    'residential.pricing.payback': 'Payback:',
    'residential.pricing.unitsPerDay': 'units/day',
    'residential.pricing.years': 'years',
    'residential.pricing.quote': 'Get Detailed Quote',
    'residential.pricing.bhk2_3': '2-3 BHK',
    'residential.pricing.bhk3_4': '3-4 BHK',
    'residential.pricing.largeHomes': 'Large Homes',
    'residential.process.title': 'Simple Installation Process',
    'residential.process.subtitle': 'From consultation to commissioning, we handle everything for you',
    'residential.process.step1.title': 'Site Visit',
    'residential.process.step1.desc': 'Free roof assessment and shadow analysis',
    'residential.process.step2.title': 'Design',
    'residential.process.step2.desc': 'Custom system design and subsidy application',
    'residential.process.step3.title': 'Installation',
    'residential.process.step3.desc': 'Professional installation in 2-3 days',
    'residential.process.step4.title': 'Activate',
    'residential.process.step4.desc': 'Net metering and system commissioning',
    'residential.comparison.title': 'System Comparison',
    'residential.comparison.ongrid.title': 'On-Grid System',
    'residential.comparison.ongrid.desc': 'No battery, grid-tied only. Lower cost but no backup during power cuts.',
    'residential.comparison.hybrid.title': 'Hybrid System ⭐',
    'residential.comparison.hybrid.desc': 'Best of both - Grid + Battery backup. Power during cuts + Net metering benefits.',
    'residential.comparison.offgrid.title': 'Off-Grid System',
    'residential.comparison.offgrid.desc': 'Complete independence with batteries. Higher cost, no net metering benefits.',
    'residential.cta.title': 'Ready to Power Your Home with Solar?',
    'residential.cta.subtitle': 'Get started with a free site assessment and personalized solar solution',
    'residential.cta.btn': 'Schedule Free Site Visit',

    // About Page
    'about.stats.experience': 'Years Experience',
    'about.stats.customers': 'Happy Customers',
    'about.stats.power': 'Power Generated',
    'about.stats.satisfaction': 'Customer Satisfaction',
    'about.purpose.title': 'Our Purpose & Vision',
    'about.purpose.subtitle': 'Driven by innovation and sustainability, we\'re committed to making solar energy accessible to every Indian.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'Empowering India with affordable, reliable solar energy solutions.',
    'about.mission.deliver': 'We Deliver',
    'about.mission.point1': 'Premium quality solar installations',
    'about.mission.point2': '24/7 customer support & maintenance',
    'about.mission.point3': 'Maximum ROI for your investment',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be India\'s most trusted solar energy company by 2030.',
    'about.vision.goals': 'Our Goals',
    'about.vision.goal1': 'Power 100,000+ homes by 2030',
    'about.vision.goal2': 'Reduce carbon footprint by 1M tons',
    'about.vision.goal3': 'Create 10,000+ green jobs',
    'about.why.title': 'Why Choose ATP Infratech?',
    'about.why.subtitle': 'Excellence in every installation, support in every step',
    'about.why.feature1.title': 'Certified Excellence',
    'about.why.feature1.desc': 'ISO certified with industry-leading warranty programs',
    'about.why.feature2.title': 'Expert Team',
    'about.why.feature2.desc': '100+ trained professionals with decades of combined experience',
    'about.why.feature3.title': 'Complete Support',
    'about.why.feature3.desc': 'From consultation to maintenance, we\'re with you every step',
    'about.cta.title': 'Ready to Go Solar?',
    'about.cta.subtitle': 'Join thousands of satisfied customers who\'ve made the switch to clean energy',
    'about.cta.btn': 'Get Your Free Consultation',


    // Commercial Service
    'commercial.hero.badge': 'Enterprise Solar Solutions',
    'commercial.hero.title': 'Transform Your Business with',
    'commercial.hero.titleHighlight': 'Solar Power',
    'commercial.hero.subtitle': 'Reduce operational costs by up to 80% with scalable commercial solar solutions. ROI in 3-4 years with tax benefits and accelerated depreciation.',
    'commercial.why.title': 'Why Businesses Choose Solar',
    'commercial.why.subtitle': 'Transform your bottom line with clean energy',
    'commercial.why.benefit1.title': 'Reduce Operating Costs',
    'commercial.why.benefit1.desc': 'Save 70-80% on electricity bills with locked-in energy rates for 25+ years',
    'commercial.why.benefit1.stat': '₹20L+ Annual Savings',
    'commercial.why.benefit2.title': 'Quick ROI & Tax Benefits',
    'commercial.why.benefit2.desc': 'Payback in 3-5 years with 40% accelerated depreciation in first year',
    'commercial.why.benefit2.stat': '40% Tax Benefit',
    'commercial.why.benefit3.title': 'Corporate Sustainability',
    'commercial.why.benefit3.desc': 'Meet ESG goals, reduce carbon footprint, and enhance brand reputation',
    'commercial.why.benefit3.stat': '100% Green Energy',
    'commercial.industries.title': 'Industry-Specific Solutions',
    'commercial.industries.subtitle': 'Tailored solar systems for every business type',
    'commercial.industries.manufacturing.title': 'Manufacturing',
    'commercial.industries.manufacturing.desc': 'Heavy power users with high daytime consumption',
    'commercial.industries.warehouses.title': 'Warehouses',
    'commercial.industries.warehouses.desc': 'Large roof space for maximum generation',
    'commercial.industries.hotels.title': 'Hotels & Resorts',
    'commercial.industries.hotels.desc': '24/7 operations with consistent energy needs',
    'commercial.industries.offices.title': 'IT Parks & Offices',
    'commercial.industries.offices.desc': 'Peak loads during business hours',
    'commercial.packages.title': 'Scalable Solar Solutions',
    'commercial.packages.subtitle': 'From small offices to large industrial facilities, we design systems that match your energy needs and budget.',
    'commercial.packages.small.title': 'Small Commercial',
    'commercial.packages.small.size': '25-50 kW',
    'commercial.packages.small.cost': '₹12-25 Lakhs',
    'commercial.packages.small.generation': '150-200 units/day',
    'commercial.packages.medium.title': 'Medium Commercial',
    'commercial.packages.medium.size': '50-100 kW',
    'commercial.packages.medium.cost': '₹25-50 Lakhs',
    'commercial.packages.medium.generation': '200-400 units/day',
    'commercial.packages.large.title': 'Large Industrial',
    'commercial.packages.large.size': '100-500 kW',
    'commercial.packages.large.cost': '₹50L-2.5 Crores',
    'commercial.packages.large.generation': '400-2000 units/day',
    'commercial.packages.mega.title': 'Mega Projects',
    'commercial.packages.mega.size': '500 kW+',
    'commercial.packages.mega.cost': 'Custom Quote',
    'commercial.packages.mega.generation': '2000+ units/day',
    'commercial.packages.dailyGen': 'Daily Generation:',
    'commercial.packages.customBtn': 'Get Custom Sizing',
    'commercial.complete.title': 'Complete Commercial Package',
    'commercial.complete.subtitle': 'Everything you need for successful solar implementation',
    'commercial.complete.audit.title': 'Energy Audit',
    'commercial.complete.audit.desc': 'Detailed consumption analysis and system sizing',
    'commercial.complete.design.title': 'Custom Design',
    'commercial.complete.design.desc': 'Tailored to your roof structure and energy needs',
    'commercial.complete.quality.title': 'Quality Assurance',
    'commercial.complete.quality.desc': 'Premium components with Tier-1 certifications',
    'commercial.complete.grid.title': 'Grid Integration',
    'commercial.complete.grid.desc': 'Seamless connection with existing power supply',
    'commercial.complete.monitoring.title': 'Performance Monitoring',
    'commercial.complete.monitoring.desc': 'Real-time tracking and optimization',
    'commercial.complete.support.title': 'O&M Support',
    'commercial.complete.support.desc': 'Comprehensive maintenance for 25+ years',
    'commercial.cta.title': "Let's Build Your Solar Solution",
    'commercial.cta.subtitle': 'Schedule a free energy audit and discover how much you can save',
    'commercial.cta.btn': 'Request Energy Audit',
    'commercial.cta.financingBtn': 'View Financing Options',

    // Products Page
    'products.hero.title': 'High-Performance',
    'products.hero.titleHighlight': 'Solar Technology',
    'products.hero.subtitle': 'We partner with world-class manufacturers to bring you the most efficient and reliable solar products in India.',
    'products.hero.badge': 'Premium Solar Products',
    'products.panels.title': 'Monocrystalline Solar Panels',
    'products.panels.desc': 'Industry-leading efficiency with premium monocrystalline technology. Our panels deliver maximum power output even in low-light conditions.',
    'products.panels.feature1': '21%+ module efficiency',
    'products.panels.feature2': '540-550W high-power modules',
    'products.panels.feature3': '25-year linear performance warranty',
    'products.panels.feature4': 'IEC/CE/ISO certified',
    'products.panels.feature5': 'PID & LID resistant technology',
    'products.panels.feature6': 'Withstands up to 2400 Pa snow load',
    'products.panels.stat1.value': '25+',
    'products.panels.stat1.label': 'Years Lifespan',
    'products.panels.stat2.value': '21%',
    'products.panels.stat2.label': 'Efficiency',
    'products.panels.stat3.value': '550W',
    'products.panels.stat3.label': 'Max Power',
    'products.inverters.title': 'Smart Solar Inverters',
    'products.inverters.desc': 'Convert DC to AC power with maximum efficiency. Our smart and hybrid inverters come with advanced monitoring, battery management, and protection features.',
    'products.inverters.type1.title': 'On-Grid Inverters',
    'products.inverters.type1.desc': 'Grid-tied systems with net metering',
    'products.inverters.type2.title': 'Hybrid Inverters',
    'products.inverters.type2.desc': 'Smart battery backup with grid connectivity',
    'products.inverters.type3.title': 'Off-Grid Inverters',
    'products.inverters.type3.desc': 'Complete energy independence',
    'products.inverters.type4.title': 'Micro Inverters',
    'products.inverters.type4.desc': 'Panel-level optimization',
    'products.inverters.feature1': 'Smart and Hybrid inverter technology',
    'products.inverters.feature2': '98%+ conversion efficiency',
    'products.inverters.feature3': 'WiFi & mobile app monitoring',
    'products.inverters.feature4': 'Battery management system',
    'products.inverters.feature5': '5-10 year warranty',
    'products.inverters.feature6': 'Overload & short circuit protection',
    'products.storage.title': 'Energy Storage Solutions',
    'products.storage.subtitle': 'Store solar energy for use anytime - day or night',
    'products.storage.battery1.title': 'Lithium-Ion Batteries',
    'products.storage.battery1.capacity': '5-15 kWh',
    'products.storage.battery1.cycles': '6000+ cycles',
    'products.storage.battery1.warranty': '10 years',
    'products.storage.battery1.feature1': 'Smart BMS',
    'products.storage.battery1.feature2': 'Fast charging',
    'products.storage.battery1.feature3': '80% DoD',
    'products.storage.battery1.feature4': 'Compact design',
    'products.storage.battery2.title': 'Lead-Acid Batteries',
    'products.storage.battery2.capacity': '150-250 Ah',
    'products.storage.battery2.cycles': '1500+ cycles',
    'products.storage.battery2.warranty': '5 years',
    'products.storage.battery2.feature1': 'Cost-effective',
    'products.storage.battery2.feature2': 'Proven technology',
    'products.storage.battery2.feature3': 'Easy maintenance',
    'products.storage.battery2.feature4': 'Wide availability',
    'products.storage.battery3.title': 'Battery Management',
    'products.storage.battery3.capacity': 'Smart Control',
    'products.storage.battery3.cycles': 'Optimized',
    'products.storage.battery3.warranty': 'Protected',
    'products.storage.battery3.feature1': 'Real-time monitoring',
    'products.storage.battery3.feature2': 'Auto protection',
    'products.storage.battery3.feature3': 'Temperature control',
    'products.storage.battery3.feature4': 'Charge optimization',
    'products.storage.capacity': 'Capacity:',
    'products.storage.cycles': 'Life Cycles:',
    'products.storage.warranty': 'Warranty:',
    'products.certifications.title': 'Quality Certifications',
    'products.certifications.subtitle': 'All products meet international quality standards',
    'products.certifications.cert1.title': 'IEC Certified',
    'products.certifications.cert1.desc': 'International standards',
    'products.certifications.cert2.title': 'ISO Certified',
    'products.certifications.cert2.desc': 'Quality management',
    'products.certifications.cert3.title': 'CE Marked',
    'products.certifications.cert3.desc': 'European conformity',
    'products.certifications.cert4.title': 'MNRE Approved',
    'products.certifications.cert4.desc': 'Government recognized',
    'products.cta.title': 'Get Expert Product Recommendations',
    'products.cta.subtitle': 'Talk to our technical experts to choose the perfect solar products for your needs',
    'products.cta.btn': 'Consult Our Experts',

    // PM Subsidy Page
    'subsidy.hero.title': 'PM Solar Rooftop',
    'subsidy.hero.titleHighlight': 'Subsidy Scheme',
    'subsidy.hero.subtitle': 'Get up to ₹108,000 subsidy on your rooftop solar installation.',
    'subsidy.hero.desc': 'Make solar affordable and accessible for every Indian household with government support.',
    'subsidy.hero.cta1': 'Apply for Subsidy',
    'subsidy.hero.cta2': 'View Financing Options',
    'subsidy.hero.badge': 'Government Approved • Up to 60% Subsidy',
    'subsidy.hero.stat1': 'Subsidy',
    'subsidy.hero.stat2': 'Max Amount',
    'subsidy.benefits.title': 'Subsidy Benefits',
    'subsidy.benefits.subtitle': 'The PM Solar Rooftop Scheme offers substantial financial support to make solar energy affordable',
    'subsidy.benefits.card1.title': 'Up to ₹1,08,000 Subsidy',
    'subsidy.benefits.card1.desc': 'For 3kW+ systems - residential sector gets maximum benefits',
    'subsidy.benefits.card2.title': '60% Cost Reduction',
    'subsidy.benefits.card2.desc': 'Subsidy covers up to 60% of your total installation cost',
    'subsidy.benefits.card3.title': 'All India Coverage',
    'subsidy.benefits.card3.desc': 'Available to residential consumers across all states',
    'subsidy.table.title': 'Subsidy Breakdown by System Capacity',
    'subsidy.table.capacity': 'System Capacity',
    'subsidy.table.rate': 'Subsidy Rate',
    'subsidy.table.max': 'Maximum Subsidy',
    'subsidy.table.investment': 'Your Investment',
    'subsidy.table.popular': 'Most Popular',
    'subsidy.table.note': 'Subsidy is directly credited to your account after installation and inspection. Costs shown are approximate and may vary based on location and system specifications.',
    'subsidy.eligibility.title': 'Eligibility',
    'subsidy.eligibility.titleHighlight': 'Criteria',
    'subsidy.eligibility.whocan.title': 'Who Can Apply?',
    'subsidy.eligibility.whocan.point1': 'Individual house owners',
    'subsidy.eligibility.whocan.point2': 'Residential welfare associations',
    'subsidy.eligibility.whocan.point3': 'Group housing societies',
    'subsidy.eligibility.whocan.point4': 'All residential consumers in India',
    'subsidy.eligibility.docs.title': 'Required Documents',
    'subsidy.eligibility.docs.point1': 'Electricity bill copy',
    'subsidy.eligibility.docs.point2': 'Aadhaar card',
    'subsidy.eligibility.docs.point3': 'PAN card',
    'subsidy.eligibility.docs.point4': 'Bank account details',
    'subsidy.eligibility.docs.point5': 'Property ownership proof',
    'subsidy.apply.title': 'How to',
    'subsidy.apply.titleHighlight': 'Apply',
    'subsidy.apply.subtitle': 'Simple 5-step process to get your solar subsidy approved',
    'subsidy.apply.step1.title': 'Register',
    'subsidy.apply.step1.desc': 'Register on the national portal',
    'subsidy.apply.step2.title': 'Select Vendor',
    'subsidy.apply.step2.desc': 'Choose ATP Infratech as your installer',
    'subsidy.apply.step3.title': 'Install System',
    'subsidy.apply.step3.desc': 'We install your solar system',
    'subsidy.apply.step4.title': 'Inspection',
    'subsidy.apply.step4.desc': 'Discom inspection and net metering',
    'subsidy.apply.step5.title': 'Get Subsidy',
    'subsidy.apply.step5.desc': 'Subsidy credited to your account',
    'subsidy.apply.cta': 'Start Your Application',
    'subsidy.apply.note': "We'll guide you through the entire process",
    'subsidy.combine.title': 'Combine Subsidy with Financing',
    'subsidy.combine.subtitle': 'Get the best of both worlds - 60% subsidy + easy EMI options',
    'subsidy.combine.cta1': 'View Financing Options',
    'subsidy.combine.cta2': 'Get Expert Consultation',

    // Financing Page
    'financing.hero.title': 'Go Solar Without',
    'financing.hero.titleHighlight': 'The Upfront Cost',
    'financing.hero.subtitle': 'Easy financing options to make solar affordable. Pay from your savings, not your pocket.',
    'financing.hero.cta1': 'Get Financing Quote',
    'financing.hero.cta2': 'View PM Subsidy',
    'financing.banner.title': 'Combine Financing with PM Solar Subsidy!',
    'financing.banner.subtitle': 'Get up to 40% subsidy + Easy EMI options = Maximum savings',
    'financing.banner.cta': 'Check Subsidy Eligibility',
    'financing.why.title': 'Why',
    'financing.why.titleHighlight': 'Finance',
    'financing.why.titleEnd': 'Your Solar?',
    'financing.why.subtitle': 'Smart financing makes solar accessible and profitable from day one',
    'financing.benefits.title': 'Why Finance Your Solar?',
    'financing.benefits.subtitle': 'Smart financing makes solar accessible and profitable from day one',
    'financing.benefits.benefit1.title': 'Lowest Interest Rate',
    'financing.benefits.benefit1.desc': 'Get attractive interest rates starting from 5-10% p.a.',
    'financing.benefits.benefit2.title': 'Lower Monthly Bills',
    'financing.benefits.benefit2.desc': 'Your EMI is less than your current electricity bill',
    'financing.benefits.benefit3.title': 'Flexible Tenure',
    'financing.benefits.benefit3.desc': 'Choose from 3 to 7 years repayment period as per your budget',
    'financing.partners.title': 'Our Financing Partners',
    'financing.partners.titleHighlight': 'Financing Partners',
    'financing.partners.subtitle': 'Partnered with leading banks and NBFCs for best interest rates',
    'financing.partners.bank.title': 'Bank Loans',
    'financing.partners.bank.interest': 'Interest Rate: 5.0% - 6.0% p.a.',
    'financing.partners.bank.interestDesc': 'Competitive rates from leading banks',
    'financing.partners.bank.tenure': 'Loan Tenure: Up to 7 years',
    'financing.partners.bank.tenureDesc': 'Flexible repayment period',
    'financing.partners.bank.processingFee': 'Processing Fee: Zero',
    'financing.partners.bank.processingFeeDesc': 'No processing charges',
    'financing.partners.bank.partners': 'Partners: SBI, Bank of Baroda (BOB), Union Bank, Punjab National Bank (PNB)',
    'financing.partners.bank.partnersDesc': 'Trusted banking partners',
    'financing.partners.nbfc.title': 'NBFC Financing for Larger Projects',
    'financing.partners.nbfc.interest': 'Interest Rate: 10% - 13% p.a.',
    'financing.partners.nbfc.interestDesc': 'Quick approval process',
    'financing.partners.nbfc.tenure': 'Loan Tenure: 3 to 5 years',
    'financing.partners.nbfc.tenureDesc': 'Faster processing',
    'financing.partners.nbfc.documentation': 'Minimal Documentation',
    'financing.partners.nbfc.documentationDesc': 'Easy approval criteria',
    'financing.partners.nbfc.partners': 'Partners: Bajaj Finserv, Tata Capital',
    'financing.partners.nbfc.partnersDesc': 'Trusted NBFC partners',
    'financing.emi.title': 'EMI Calculation Examples',
    'financing.emi.titleHighlight': 'Calculation Examples',
    'financing.emi.subtitle': 'See how affordable solar can be with easy monthly payments',
    'financing.emi.tableTitle': 'Monthly Payment Breakdown - 5kW System',
    'financing.emi.tenure': 'Tenure',
    'financing.emi.systemCost': 'System Cost',
    'financing.emi.afterSubsidy': 'After Subsidy',
    'financing.emi.monthlyEmi': 'Monthly EMI',
    'financing.emi.savings': 'Savings',
    'financing.emi.years3': '3 Years',
    'financing.emi.years5': '5 Years (Popular)',
    'financing.emi.years7': '7 Years',
    'financing.emi.example': 'Example: With ₹11,500 average electricity bill, your EMI is still less than your current bill. You start saving from month one! After loan completion, enjoy 100% free electricity.',
    'financing.combo.title': 'PM Subsidy + Financing = Best Deal',
    'financing.combo.subtitle': 'Maximize your savings by combining government subsidy with easy financing',
    'financing.combo.subsidy.title': 'Up to ₹1,08,000 Subsidy',
    'financing.combo.subsidy.desc': 'Government covers 60% of your solar system cost',
    'financing.combo.subsidy.btn': 'Learn More',
    'financing.combo.interest.title': 'Lowest Interest Rate',
    'financing.combo.interest.desc': 'Get attractive interest rates starting from 5-10% p.a.',
    'financing.combo.interest.btn': 'Apply Now',
    'financing.combo.lowestEmi.title': 'Lowest EMI',
    'financing.combo.lowestEmi.desc': 'Pay less monthly than your current electricity bill',
    'financing.combo.lowestEmi.btn': 'Calculate EMI',
    'financing.comparison.title': 'Compare: Regular Bills vs Solar + Financing',
    'financing.comparison.without.title': 'Without Solar',
    'financing.comparison.without.bill': '₹11,500/month',
    'financing.comparison.without.current': 'Current electricity bill',
    'financing.comparison.without.total': '25 Year Total: ₹34,50,000',
    'financing.comparison.with.title': 'With Solar + Financing',
    'financing.comparison.with.emi': '₹4,500/month',
    'financing.comparison.with.desc': 'EMI for 5 years, then ₹0',
    'financing.comparison.with.total': '25 Year Total: ₹2,70,000 + zero bills for 20 years',
    'financing.comparison.totalSavings': 'Total Savings in 25 Years',
    'financing.comparison.amount': '₹31,80,000',
    'financing.comparison.points.p1': 'Pay only ₹4,500/month instead of ₹11,500',
    'financing.comparison.points.p2': 'After 5 years: Zero electricity bills',
    'financing.comparison.points.p3': '25-year panel warranty included',
    'financing.comparison.points.btn': 'Calculate Your Savings',
    'financing.process.title': 'How to Get Financing',
    'financing.process.step1.number': '1',
    'financing.process.step1.title': 'Contact Us',
    'financing.process.step1.desc': 'Share your requirements',
    'financing.process.step2.number': '2',
    'financing.process.step2.title': 'Get Quote',
    'financing.process.step2.desc': 'Receive customized proposal',
    'financing.process.step3.number': '3',
    'financing.process.step3.title': 'Apply for Loan',
    'financing.process.step3.desc': 'We help with documentation',
    'financing.process.step4.number': '4',
    'financing.process.step4.title': 'Installation',
    'financing.process.step4.desc': 'Quick setup and start saving',
    'financing.process.applyBtn': 'Apply Now',
    'financing.process.subsidyBtn': 'View Subsidy Details',
    'financing.cta.title': 'Ready to Make Solar Affordable?',

    // Maintenance Page
    'maintenance.hero.badge': 'Professional Care • 24/7 Support',
    'maintenance.hero.title': 'Maintenance &',
    'maintenance.hero.subtitle': 'Support Services',
    'maintenance.hero.desc': 'Keep your solar system running at peak performance with our comprehensive maintenance and real-time monitoring services.',
    'maintenance.why.title': 'Why',
    'maintenance.why.titleHighlight': 'Regular Maintenance',
    'maintenance.why.titleEnd': 'Matters',
    'maintenance.why.subtitle': 'Proper maintenance ensures maximum energy generation and extends system lifespan',
    'maintenance.why.output.title': '20-30% More Output',
    'maintenance.why.output.desc': 'Clean panels generate significantly more power than dirty ones',
    'maintenance.why.lifespan.title': 'Extended Lifespan',
    'maintenance.why.lifespan.desc': 'Regular maintenance can extend system life from 25 to 30+ years',
    'maintenance.why.downtime.title': 'Prevent Downtime',
    'maintenance.why.downtime.desc': 'Early detection of issues prevents costly repairs and energy loss',
    'maintenance.services.title': 'Our',
    'maintenance.services.titleHighlight': 'Maintenance Services',
    'maintenance.services.cleaning.title': 'Panel Cleaning Service',
    'maintenance.services.cleaning.desc': 'Professional cleaning to remove dust, bird droppings, and debris that reduce efficiency.',
    'maintenance.services.cleaning.feat1': 'Waterless or water-based cleaning methods',
    'maintenance.services.cleaning.feat2': 'Safe cleaning agents that won\'t damage panels',
    'maintenance.services.cleaning.feat3': 'Quarterly cleaning schedule recommended',
    'maintenance.services.cleaning.feat4': 'Before/after output comparison report',
    'maintenance.services.cleaning.price': 'Starting ₹2/watt',
    'maintenance.services.monitoring.title': '24/7 Monitoring System',
    'maintenance.services.monitoring.desc': 'Real-time monitoring to track performance and detect issues instantly.',
    'maintenance.services.monitoring.feat1': 'Cloud-based monitoring platform',
    'maintenance.services.monitoring.feat2': 'Mobile app access for real-time data',
    'maintenance.services.monitoring.feat3': 'Instant alerts for system failures',
    'maintenance.services.monitoring.feat4': 'Daily, weekly, and monthly reports',
    'maintenance.services.monitoring.price': 'Custom monitoring fees',
    'maintenance.services.checkup.title': 'Regular Check-ups',
    'maintenance.services.checkup.desc': 'Comprehensive system inspections to ensure optimal performance.',
    'maintenance.services.checkup.feat1': 'Inverter health and performance checks',
    'maintenance.services.checkup.feat2': 'Electrical connection inspections',
    'maintenance.services.checkup.feat3': 'Mounting structure stability checks',
    'maintenance.services.checkup.feat4': 'Panel hotspot detection using thermal imaging',
    'maintenance.services.checkup.price': 'Semi-annual inspections: ₹3,000/visit',
    'maintenance.services.repair.title': 'Troubleshooting & Repair',
    'maintenance.services.repair.desc': 'Quick response to system issues with expert technical support.',
    'maintenance.services.repair.feat1': '24-hour emergency response',
    'maintenance.services.repair.feat2': 'Inverter replacement and repair',
    'maintenance.services.repair.feat3': 'Panel replacement (if under warranty)',
    'maintenance.services.repair.feat4': 'Wiring and connection fixes',
    'maintenance.services.repair.price': 'On-demand pricing based on issue',
    'maintenance.amc.title': 'Annual',
    'maintenance.amc.titleHighlight': 'Maintenance Packages',
    'maintenance.amc.subtitle': 'Choose a comprehensive package and save up to 30% on maintenance costs',
    'maintenance.packages.basic.title': 'Basic',
    'maintenance.packages.basic.price': '₹4,999/year',
    'maintenance.packages.basic.desc': 'Perfect for small systems (up to 3kW)',
    'maintenance.packages.basic.feat1': '2 cleaning sessions/year',
    'maintenance.packages.basic.feat2': '1 system inspection',
    'maintenance.packages.basic.feat3': 'Email performance reports',
    'maintenance.packages.basic.feat4': 'Phone support',
    'maintenance.packages.basic.btn': 'Choose Plan',
    'maintenance.packages.standard.title': 'Standard',
    'maintenance.packages.standard.badge': 'Most Popular',
    'maintenance.packages.standard.price': '₹7,999/year',
    'maintenance.packages.standard.desc': 'Best value for 3-5kW systems',
    'maintenance.packages.standard.feat1': '4 cleaning sessions/year',
    'maintenance.packages.standard.feat2': '2 comprehensive inspections',
    'maintenance.packages.standard.feat3': '24/7 monitoring included',
    'maintenance.packages.standard.feat4': 'Priority support',
    'maintenance.packages.standard.feat5': '20% discount on repairs',
    'maintenance.packages.standard.btn': 'Choose Plan',
    'maintenance.packages.premium.title': 'Premium',
    'maintenance.packages.premium.price': '₹12,999/year',
    'maintenance.packages.premium.desc': 'Complete care for 5kW+ systems',
    'maintenance.packages.premium.feat1': '6 cleaning sessions/year',
    'maintenance.packages.premium.feat2': '4 comprehensive inspections',
    'maintenance.packages.premium.feat3': '24/7 monitoring + alerts',
    'maintenance.packages.premium.feat4': 'VIP support (2-hour response)',
    'maintenance.packages.premium.feat5': '30% discount on repairs',
    'maintenance.packages.premium.feat6': 'Free thermal imaging check',
    'maintenance.packages.premium.btn': 'Choose Plan',
    'maintenance.cta.title': 'Schedule Your Maintenance Today',
    'maintenance.cta.subtitle': 'Keep your solar system performing at its best with our professional maintenance services',
    'maintenance.cta.btn': 'Request Maintenance',
    'maintenance.cta.phone': 'Call +91 73806 07555',

    // Solar Calculator Page
    'calculator.hero.badge': 'Free Solar Calculator',
    'calculator.hero.title': 'Calculate Your',
    'calculator.hero.titleHighlight': 'Solar Savings',
    'calculator.hero.subtitle': 'Discover how much you can save with solar energy. Get instant estimates on system size, costs, and payback period.',
    'calculator.form.title': 'Enter Your Details',
    'calculator.form.monthlyBill': 'Monthly Electricity Bill (₹)',
    'calculator.form.roofArea': 'Available Roof Area (sq ft)',
    'calculator.form.location': 'Your Location',
    'calculator.form.systemType': 'System Type',
    'calculator.form.systemType.onGrid': 'On-Grid (No Battery)',
    'calculator.form.systemType.hybrid': 'Hybrid (With Battery)',
    'calculator.form.systemType.offGrid': 'Off-Grid (Complete Backup)',
    'calculator.form.calculate': 'Calculate Savings',
    'calculator.results.title': 'Your Solar Savings Report',
    'calculator.results.systemSize': 'Recommended System Size',
    'calculator.results.totalCost': 'Total System Cost',
    'calculator.results.subsidy': 'Government Subsidy',
    'calculator.results.finalCost': 'Your Final Investment',
    'calculator.results.monthlySavings': 'Monthly Savings',
    'calculator.results.yearlySavings': 'Yearly Savings',
    'calculator.results.payback': 'Payback Period',
    'calculator.results.lifetimeSavings': '25-Year Savings',
    'calculator.results.co2Reduction': 'CO₂ Reduction',
    'calculator.benefits.title': 'Your Benefits Include',
    'calculator.benefits.point1': 'Up to 90% reduction in electricity bills',
    'calculator.benefits.point2': '60% government subsidy on system cost',
    'calculator.benefits.point3': '25-year performance warranty',
    'calculator.benefits.point4': 'Increase property value by 3-4%',
    'calculator.benefits.point5': 'Zero maintenance for 5+ years',
    'calculator.benefits.point6': '24/7 monitoring and support',
    'calculator.cta.title': 'Ready to Go Solar?',
    'calculator.cta.subtitle': 'Get a detailed quote from our experts',
    'calculator.cta.button': 'Get Free Consultation',

    // Hybrid Solar
    'hybrid.title': 'Hybrid Solar Systems',
    'hybrid.subtitle': 'Best of both worlds - Grid connectivity with battery backup',
    'hybrid.desc': 'Hybrid solar systems combine the benefits of on-grid and off-grid systems, providing you with grid connectivity while having battery backup for power cuts.',
    'hybrid.benefit1': 'Use solar during day, grid at night',
    'hybrid.benefit2': 'Battery backup during power cuts',
    'hybrid.benefit3': 'Net metering for excess power',
    'hybrid.benefit4': 'Smart power management',
    'hybrid.benefit5': 'Reduce dependency on grid',
    'hybrid.benefit6': 'Lower electricity bills',

    // Popup
    'popup.title': 'PM Solar Subsidy Available!',
    'popup.subtitle': 'Get up to 60% subsidy on your rooftop solar installation',
    'popup.benefits': 'Benefits include:',
    'popup.point1': 'Up to ₹1,08,000 subsidy for 3kW+ systems',
    'popup.point2': 'Save up to 90% on electricity bills',
    'popup.point3': 'Government-backed scheme with easy application',
    'popup.point4': 'Combined with easy financing options',
    'popup.cta1': 'Check Eligibility',
    'popup.cta2': 'View Financing',
    'popup.note': 'Limited time offer • Government approved • Quick processing',
  },
  hi: {
    // Common
    'common.learnMore': 'और जानें',
    'common.getQuote': 'मुफ्त कोटेशन पाएं',
    'common.readMore': 'और पढ़ें',
    'common.contactUs': 'संपर्क करें',
    'common.apply': 'अभी आवेदन करें',
    
    // Navbar
    'nav.home': 'होम',
    'nav.services': 'सेवाएं',
    'nav.allServices': 'सभी सेवाएं',
    'nav.allServicesDesc': 'संपूर्ण सोलर समाधान',
    'nav.residential': 'रेजिडेंशियल सोलर',
    'nav.residentialDesc': 'घरों के लिए रूफटॉप समाधान',
    'nav.commercial': 'कमर्शियल सोलर',
    'nav.commercialDesc': 'बड़े व्यवसायों के लिए समाधान',
    'nav.maintenance': 'मेंटेनेंस और सपोर्ट',
    'nav.maintenanceDesc': '24/7 निगरानी और सफाई',
    'nav.resources': 'संसाधन',
    'nav.financing': 'फाइनेंसिंग विकल्प',
    'nav.financingDesc': 'आसान EMI और लोन योजनाएं',
    'nav.pmSubsidy': 'PM सोलर सब्सिडी',
    'nav.pmSubsidyDesc': 'सरकारी योजनाएं और लाभ',
    'nav.products': 'उत्पाद',
    'nav.productsDesc': 'उच्च-प्रदर्शन सोलर पैनल',
    'nav.calculator': 'सोलर कैलकुलेटर',
    'nav.calculatorDesc': 'अपनी बचत की गणना करें',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क करें',
    'nav.getQuote': 'मुफ्त कोटेशन पाएं',

    // Footer
    'footer.company': 'ATP इंफ्राटेक',
    'footer.description': 'भारत में अग्रणी सोलर समाधान प्रदाता। घरों और व्यवसायों को स्वच्छ, टिकाऊ ऊर्जा से सशक्त बनाना।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.services': 'सेवाएं',
    'footer.solarConsultation': 'सोलर परामर्श',
    'footer.contactUs': 'संपर्क करें',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',

    // Home Page
    'home.hero.title': 'अपने भविष्य को शक्ति दें',
    'home.hero.titleHighlight': 'स्वच्छ सोलर ऊर्जा',
    'home.hero.subtitle': 'बिजली बिल में 90% तक की बचत करें। ₹108,000 तक की सरकारी सब्सिडी पाएं। भारत भर में 10,000+ खुश ग्राहकों के साथ जुड़ें।',
    'home.hero.cta1': 'मुफ्त परामर्श पाएं',
    'home.hero.cta2': 'बचत की गणना करें',
    
    'home.whyChoose.title': 'सोलर ऊर्जा क्यों चुनें?',
    'home.whyChoose.subtitle': 'कई लाभ जो सोलर को सबसे स्मार्ट निवेश बनाते हैं',
    'home.whyChoose.saveMoney': 'पैसे बचाएं',
    'home.whyChoose.saveMoneyDesc': 'बिजली बिल में 70-90% की कटौती',
    'home.whyChoose.govSubsidy': 'सरकारी सब्सिडी',
    'home.whyChoose.govSubsidyDesc': '₹108,000 तक की सब्सिडी पाएं',
    'home.whyChoose.ecoFriendly': 'पर्यावरण के अनुकूल',
    'home.whyChoose.ecoFriendlyDesc': 'शून्य उत्सर्जन, स्वच्छ ऊर्जा',
    'home.whyChoose.increaseValue': 'संपत्ति मूल्य बढ़ाएं',
    'home.whyChoose.increaseValueDesc': 'घर का मूल्य 3-4% बढ़ाएं',

    'home.solutions.title': 'संपूर्ण सोलर समाधान',
    'home.solutions.residential': 'रेजिडेंशियल सोलर',
    'home.solutions.residentialDesc': 'घरों और अपार्टमेंट के लिए एकदम सही। बिजली बिल पर सालाना ₹30,000+ की बचत।',
    'home.solutions.commercial': 'कमर्शियल सोलर',
    'home.solutions.commercialDesc': 'व्यवसायों और उद्योगों के लिए आदर्श। परिचालन लागत में 80% की कमी।',
    'home.solutions.maintenance': 'मेंटेनेंस और सपोर्ट',
    'home.solutions.maintenanceDesc': '24/7 निगरानी और रखरखाव। अपने सिस्टम को उच्चतम प्रदर्शन पर बनाए रखें।',
    'home.solutions.learnMore': 'और जानें',

    'home.subsidy.badge': 'सरकारी पहल',
    'home.subsidy.title': '₹108,000 तक पाएं',
    'home.subsidy.titleHighlight': 'PM सोलर सब्सिडी',
    'home.subsidy.desc': 'भारत सरकार रेजिडेंशियल रूफटॉप सोलर इंस्टॉलेशन के लिए पर्याप्त सब्सिडी प्रदान करती है। सिस्टम लागत पर 60% सब्सिडी पाएं।',
    'home.subsidy.point1': '1 kW सिस्टम के लिए ₹60,000 सब्सिडी',
    'home.subsidy.point2': '2-3 kW सिस्टम के लिए ₹90,000 सब्सिडी',
    'home.subsidy.point3': '3+ kW सिस्टम के लिए ₹1,08,000 सब्सिडी',
    'home.subsidy.cta': 'अपनी पात्रता जांचें',

    'home.testimonials.title': 'हमारे ग्राहक क्या कहते हैं',
    'home.testimonials.subtitle': 'भारत भर में हजारों संतुष्ट सोलर उपयोगकर्ताओं से जुड़ें',

    // Testimonials
    'testimonial.1.name': 'राजेश कुमार',
    'testimonial.1.location': 'लखनऊ, उत्तर प्रदेश',
    'testimonial.1.text': 'ATP इंफ्राटेक ने मेरी छत पर 5kW सिस्टम स्थापित किया। PM सब्सिडी के साथ, मैंने केवल 60% लागत का भुगतान किया। मेरा बिजली बिल ₹8,000 से घटकर ₹800 हो गया!',
    'testimonial.1.savings': '90% बिल में कमी',
    'testimonial.2.name': 'प्रिया शर्मा',
    'testimonial.2.location': 'नोएडा, उत्तर प्रदेश',
    'testimonial.2.text': 'फाइनेंसिंग विकल्प ने हमारे लिए सोलर को किफायती बना दिया। आसान EMI और पूरी स्थापना प्रक्रिया में उत्कृष्ट ग्राहक सहायता।',
    'testimonial.2.savings': 'शून्य डाउन पेमेंट',
    'testimonial.3.name': 'अमित पटेल',
    'testimonial.3.location': 'वाराणसी, उत्तर प्रदेश',
    'testimonial.3.text': 'कमर्शियल स्थापना केवल 2 सप्ताह में पूरी हो गई। पेशेवर टीम और उच्च गुणवत्ता वाले पैनल। 3.5 वर्षों में ROI प्राप्त किया!',
    'testimonial.3.savings': '3.5 साल का पेबैक',
    'testimonial.4.name': 'सुनीता वर्मा',
    'testimonial.4.location': 'कानपुर, उत्तर प्रदेश',
    'testimonial.4.text': 'मेंटेनेंस सेवा उत्कृष्ट है। नियमित सफाई और निगरानी अधिकतम दक्षता सुनिश्चित करती है। भविष्य के लिए बेहतरीन निवेश!',
    'testimonial.4.savings': '24/7 निगरानी',
    'testimonial.5.name': 'विक्रम सिंह',
    'testimonial.5.location': 'आगरा, उत्तर प्रदेश',
    'testimonial.5.text': 'मेरे घर के लिए सबसे अच्छा निर्णय! हाइब्रिड इन्वर्टर सिस्टम बिजली कट के दौरान भी पूरी तरह से काम करता है। अब मेरे पास 24/7 बिजली बैकअप है।',
    'testimonial.5.savings': 'पूर्ण बैकअप',
    'testimonial.6.name': 'मीरा गुप्ता',
    'testimonial.6.location': 'गाजियाबाद, उत्तर प्रदेश',
    'testimonial.6.text': 'शुरुआत से अंत तक उत्कृष्ट सेवा। स्मार्ट मॉनिटरिंग ऐप मुझे दैनिक बचत ट्रैक करने में मदद करता है। अत्यधिक अनुशंसित!',
    'testimonial.6.savings': 'स्मार्ट मॉनिटरिंग',

    'home.cta.title': 'सोलर के लिए तैयार हैं?',
    'home.cta.subtitle': 'मुफ्त परामर्श प्राप्त करें और आज से बिजली बिल पर बचत शुरू करें',
    'home.cta.button': 'अभी मुफ्त कोटेशन पाएं',

    // About Page
    'about.hero.badge': '2023 से अग्रणी सोलर इनोवेशन',
    'about.hero.title': 'भारत के',
    'about.hero.titleHighlight': 'स्वच्छ ऊर्जा',
    'about.hero.titleEnd': 'भविष्य को शक्ति देना',
    'about.hero.subtitle': 'ATP इंफ्राटेक भारत में सोलर क्रांति के अग्रणी में है, जीवन और व्यवसायों को बदलने वाले टिकाऊ ऊर्जा समाधान प्रदान करता है।',
    'about.hero.cta1': 'हमारे साथ साझेदारी करें',
    'about.hero.cta2': 'सेवाएं देखें',
    'about.stats.experience': 'वर्षों का अनुभव',
    'about.stats.customers': 'खुश ग्राहक',
    'about.stats.power': 'उत्पन्न बिजली',
    'about.stats.satisfaction': 'ग्राहक संतुष्टि',
    'about.purpose.title': 'हमारा उद्देश्य और विज़न',
    'about.purpose.subtitle': 'नवाचार और स्थिरता से प्रेरित, हम हर भारतीय के लिए सौर ऊर्जा को सुलभ बनाने के लिए प्रतिबद्ध हैं।',
    'about.mission.title': 'हमारा मिशन',
    'about.mission.desc': 'किफायती, विश्वसनीय सौर ऊर्जा समाधानों के साथ भारत को सशक्त बनाना।',
    'about.mission.deliver': 'हम प्रदान करते हैं',
    'about.mission.point1': 'प्रीमियम गुणवत्ता सौर इंस्टॉलेशन',
    'about.mission.point2': '24/7 ग्राहक सहायता और रखरखाव',
    'about.mission.point3': 'आपके निवेश पर अधिकतम ROI',
    'about.vision.title': 'हमारा विज़न',
    'about.vision.desc': '2030 तक भारत की सबसे भरोसेमंद सौर ऊर्जा कंपनी बनना।',
    'about.vision.goals': 'हमारे लक्ष्य',
    'about.vision.goal1': '2030 तक 100,000+ घरों को बिजली देना',
    'about.vision.goal2': '1M टन तक कार्बन फुटप्रिंट कम करना',
    'about.vision.goal3': '10,000+ हरित नौकरियां बनाना',
    'about.why.title': 'ATP इंफ्राटेक को क्यों चुनें?',
    'about.why.subtitle': 'हर इंस्टॉलेशन में उत्कृष्टता, हर कदम में सहायता',
    'about.why.feature1.title': 'प्रमाणित उत्कृष्टता',
    'about.why.feature1.desc': 'उद्योग-अग्रणी वारंटी कार्यक्रमों के साथ ISO प्रमाणित',
    'about.why.feature2.title': 'विशेषज्ञ टीम',
    'about.why.feature2.desc': 'दशकों के संयुक्त अनुभव के साथ 100+ प्रशिक्षित पेशेवर',
    'about.why.feature3.title': 'पूर्ण सहायता',
    'about.why.feature3.desc': 'परामर्श से रखरखाव तक, हम हर कदम पर आपके साथ हैं',
    'about.cta.title': 'सोलर के लिए तैयार हैं?',
    'about.cta.subtitle': 'हजारों संतुष्ट ग्राहकों में शामिल हों जिन्होंने स्वच्छ ऊर्जा पर स्विच किया है',
    'about.cta.btn': 'अपना मुफ्त परामर्श प्राप्त करें',


    // Contact Page
    'contact.hero.badge': 'आइए जुड़ें',
    'contact.hero.title': 'अपना',
    'contact.hero.titleHighlight': 'मुफ्त सोलर कोटेशन',
    'contact.hero.titleEnd': 'पाएं',
    'contact.hero.subtitle': 'सोलर के लिए तैयार हैं? हमारे विशेषज्ञ हर कदम पर आपकी मदद के लिए यहां हैं। आज ही व्यक्तिगत परामर्श प्राप्त करें।',
    'contact.form.title': 'हमें संदेश भेजें',
    'contact.form.subtitle': 'फॉर्म भरें और हम 24 घंटे के भीतर आपसे संपर्क करेंगे',
    'contact.form.name': 'पूरा नाम',
    'contact.form.phone': 'फोन नंबर',
    'contact.form.email': 'ईमेल पता',
    'contact.form.service': 'सेवा में रुचि',
    'contact.form.message': 'आपका संदेश',
    'contact.form.submit': 'पूछताछ भेजें',
    'contact.form.privacy': 'इस फॉर्म को सबमिट करके, आप हमारी गोपनीयता नीति और सेवा की शर्तों से सहमत होते हैं।',
    'contact.confirmation.title': 'धन्यवाद!',
    'contact.confirmation.message': 'आपकी पूछताछ सफलतापूर्वक जमा कर दी गई है। हमारी टीम आपकी सोलर आवश्यकताओं पर चर्चा करने के लिए 24 घंटे के भीतर आपसे संपर्क करेगी।',
    'contact.confirmation.button': 'बंद करें',
    
    'contact.info.title': 'संपर्क जानकारी',
    'contact.info.address': 'कार्यालय का पता',
    'contact.info.phone': 'फोन नंबर',
    'contact.info.email': 'हमें ईमेल करें',
    'contact.info.hours': 'व्यावसायिक घंटे',
    'contact.info.hoursValue': 'सोमवार - शनिवार: सुबह 9:00 - शाम 6:00\nरविवार: केवल नियुक्ति के द्वारा',

    'contact.experts.title': 'हमारे विशेषज्ञों से बात करें',
    'contact.experts.subtitle': 'हमारी प्रमाणित टीम से व्यक्तिगत सोलर समाधान प्राप्त करें',
    'contact.why.title': 'ATP इंफ्राटेक क्यों चुनें?',
    'contact.why.point1': '8+ वर्षों की सोलर उत्कृष्टता',
    'contact.why.point2': '10,000+ खुश ग्राहक',
    'contact.why.point3': 'ISO प्रमाणित इंस्टॉलेशन',
    'contact.why.point4': '25 साल की प्रदर्शन वारंटी',
    'contact.why.point5': '24/7 ग्राहक सहायता',

    // Financing Page
    'financing.hero.title': 'बिना',
    'financing.hero.titleHighlight': 'अग्रिम लागत के',
    'financing.hero.titleEnd': 'सोलर लगाएं',
    'financing.hero.subtitle': 'सोलर को किफायती बनाने के लिए आसान फाइनेंसिंग विकल्प। अपनी जेब से नहीं, अपनी बचत से भुगतान करें।',
    'financing.hero.cta1': 'फाइनेंसिंग कोटेशन प्राप्त करें',
    'financing.hero.cta2': 'PM सब्सिडी देखें',
    'financing.banner.title': 'फाइनेंसिंग को PM सोलर सब्सिडी के साथ जोड़ें!',
    'financing.banner.subtitle': 'अधिकतम बचत के लिए 40% तक सब्सिडी + आसान EMI विकल्प पाएं',
    'financing.banner.cta': 'सब्सिडी पात्रता जांचें',
    'financing.subsidy.title': 'PM सौर सब्सिडी के साथ वित्तपोषण को मिलाएं!',
    'financing.subsidy.subtitle': '40% तक की सब्सिडी + आसान EMI विकल्प = अधिकतम बचत',
    'financing.subsidy.btn': 'सब्सिडी पात्रता जांचें',
    'financing.why.title': 'अपने सोलर को',
    'financing.why.titleHighlight': 'फाइनेंस',
    'financing.why.titleEnd': 'क्यों करें?',
    'financing.why.subtitle': 'स्मार्ट फाइनेंसिंग पहले दिन से सोलर को सुलभ और लाभदायक बनाती है',
    'financing.why.interest.title': 'सबसे कम ब्याज दर',
    'financing.why.interest.desc': '5-10% प्रति वर्ष से शुरू होने वाली आकर्षक ब्याज दरें प्राप्त करें',
    'financing.why.bills.title': 'कम मासिक बिल',
    'financing.why.bills.desc': 'आपकी EMI आपके वर्तमान बिजली बिल से कम है',
    'financing.why.tenure.title': 'लचीली अवधि',
    'financing.why.tenure.desc': 'अपने बजट के अनुसार 3 से 7 साल की पुनर्भुगतान अवधि चुनें',
    'financing.benefits.title': 'अपने सोलर को फाइनेंस क्यों करें?',
    'financing.benefits.subtitle': 'स्मार्ट फाइनेंसिंग पहले दिन से सोलर को सुलभ और लाभदायक बनाती है',
    'financing.benefits.benefit1.title': 'सबसे कम ब्याज दर',
    'financing.benefits.benefit1.desc': '5-10% प्रति वर्ष से शुरू होने वाली आकर्षक ब्याज दरें प्राप्त करें',
    'financing.benefits.benefit2.title': 'कम मासिक बिल',
    'financing.benefits.benefit2.desc': 'आपकी EMI आपके वर्तमान बिजली बिल से कम है',
    'financing.benefits.benefit3.title': 'लचीली अवधि',
    'financing.benefits.benefit3.desc': 'अपने बजट के अनुसार 3 से 7 साल की पुनर्भुगतान अवधि चुनें',
    'financing.partners.title': 'हमारे फाइनेंसिंग पार्टनर',
    'financing.partners.titleHighlight': 'फाइनेंसिंग पार्टनर',
    'financing.partners.subtitle': 'सर्वोत्तम ब्याज दरों के लिए अग्रणी बैंकों और NBFCs के साथ साझेदारी',
    'financing.partners.bank.title': 'बैंक ऋण',
    'financing.partners.bank.interest': 'ब्याज दर: 5.0% - 6.0% प्रति वर्ष',
    'financing.partners.bank.interestDesc': 'अग्रणी बैंकों से प्रतिस्पर्धी दरें',
    'financing.partners.bank.tenure': 'ऋण अवधि: 7 साल तक',
    'financing.partners.bank.tenureDesc': 'लचीली पुनर्भुगतान अवधि',
    'financing.partners.bank.processingFee': 'प्रसंस्करण शुल्क: शून्य',
    'financing.partners.bank.processingFeeDesc': 'कोई प्रसंस्करण शुल्क नहीं',
    'financing.partners.bank.partners': 'भागीदार: SBI, बैंक ऑफ बड़ौदा (BOB), यूनियन बैंक, पंजाब नेशनल बैंक (PNB)',
    'financing.partners.bank.partnersDesc': 'विश्वसनीय बैंकिंग भागीदार',
    'financing.partners.nbfc.title': 'बड़ी परियोजनाओं के लिए NBFC वित्तपोषण',
    'financing.partners.nbfc.interest': 'ब्याज दर: 10% - 13% प्रति वर्ष',
    'financing.partners.nbfc.interestDesc': 'त्वरित अनुमोदन प्रक्रिया',
    'financing.partners.nbfc.tenure': 'ऋण अवधि: 3 से 5 साल',
    'financing.partners.nbfc.tenureDesc': 'तेज़ प्रसंस्करण',
    'financing.partners.nbfc.documentation': 'न्यूनतम दस्तावेज़ीकरण',
    'financing.partners.nbfc.documentationDesc': 'आसान अनुमोदन मानदंड',
    'financing.partners.nbfc.partners': 'भागीदार: बजाज फिनसर्व, टाटा कैपिटल',
    'financing.partners.nbfc.partnersDesc': 'विश्वसनीय NBFC भागीदार',
    'financing.emi.title': 'EMI गणना उदाहरण',
    'financing.emi.titleHighlight': 'गणना उदाहरण',
    'financing.emi.subtitle': 'देखें कि आसान मासिक भुगतान के साथ सोलर कितना किफायती हो सकता है',
    'financing.emi.tableTitle': 'मासिक भुगतान विवरण - 5kW सिस्टम',
    'financing.emi.tenure': 'अवधि',
    'financing.emi.systemCost': 'सिस्टम लागत',
    'financing.emi.afterSubsidy': 'सब्सिडी के बाद',
    'financing.emi.monthlyEmi': 'मासिक EMI',
    'financing.emi.savings': 'बचत',
    'financing.emi.years3': '3 साल',
    'financing.emi.years5': '5 साल (लोकप्रिय)',
    'financing.emi.years7': '7 साल',
    'financing.emi.example': 'उदाहरण: ₹11,500 औसत बिजली बिल के साथ, आपकी EMI भी आपके वर्तमान बिल से कम है। आप पहले महीने से बचत शुरू करते हैं! ऋण पूरा होने के बाद, 100% मुफ्त बिजली का आनंद लें।',
    'financing.combo.title': 'PM सब्सिडी + वित्तपोषण = सर्वोत्तम सौदा',
    'financing.combo.subtitle': 'सरकारी सब्सिडी को आसान वित्तपोषण के साथ मिलाकर अपनी बचत को अधिकतम करें',
    'financing.combo.subsidy.title': '₹1,08,000 तक की सब्सिडी',
    'financing.combo.subsidy.desc': 'सरकार आपकी सौर प्रणाली लागत का 60% कवर करती है',
    'financing.combo.subsidy.btn': 'और जानें',
    'financing.combo.interest.title': 'सबसे कम ब्याज दर',
    'financing.combo.interest.desc': '5-10% प्रति वर्ष से शुरू होने वाली आकर्षक ब्याज दरें प्राप्त करें',
    'financing.combo.interest.btn': 'अभी आवेदन करें',
    'financing.combo.lowestEmi.title': 'सबसे कम EMI',
    'financing.combo.lowestEmi.desc': 'अपने वर्तमान बिजली बिल से कम मासिक भुगतान करें',
    'financing.combo.lowestEmi.btn': 'EMI की गणना करें',
    'financing.combo.example.title': 'उदाहरण: 3kW सिस्टम',
    'financing.combo.example.totalCost': 'कुल लागत: ₹3,00,000',
    'financing.combo.example.subsidy': 'PM सब्सिडी: -₹1,08,000 (60%)',
    'financing.combo.example.yourCost': 'आपकी लागत: ₹1,92,000',
    'financing.combo.example.emi': 'EMI (5 साल): केवल ₹3,500/महीने',
    'financing.combo.example.monthlySavings': 'आपकी मासिक बचत: पहले दिन से ₹7,000+!',
    'financing.combo.example.btn': 'अपना कस्टम उद्धरण प्राप्त करें',
    'financing.comparison.title': 'तुलना करें: नियमित बिल बनाम सौर + वित्तपोषण',
    'financing.comparison.without.title': 'सौर के बिना',
    'financing.comparison.without.bill': '₹11,500/महीने',
    'financing.comparison.without.current': 'वर्तमान बिजली बिल',
    'financing.comparison.without.total': '25 साल कुल: ₹34,50,000',
    'financing.comparison.with.title': 'सौर + वित्तपोषण के साथ',
    'financing.comparison.with.emi': '₹4,500/महीने',
    'financing.comparison.with.desc': '5 साल के लिए EMI, फिर ₹0',
    'financing.comparison.with.total': '25 साल कुल: ₹2,70,000 + 20 साल के लिए शून्य बिल',
    'financing.comparison.totalSavings': '25 साल में कुल बचत',
    'financing.comparison.amount': '₹31,80,000',
    'financing.comparison.points.p1': '₹11,500 के बजाय केवल ₹4,500/महीने भुगतान करें',
    'financing.comparison.points.p2': '5 साल के बाद: शून्य बिजली बिल',
    'financing.comparison.points.p3': '25 साल की पैनल वारंटी शामिल',
    'financing.comparison.points.btn': 'अपनी बचत की गणना करें',
    'financing.process.title': 'वित्तपोषण कैसे प्राप्त करें',
    'financing.process.step1.number': '1',
    'financing.process.step1.title': 'हमसे संपर्क करें',
    'financing.process.step1.desc': 'अपनी आवश्यकताएं साझा करें',
    'financing.process.step2.number': '2',
    'financing.process.step2.title': 'उद्धरण प्राप्त करें',
    'financing.process.step2.desc': 'अनुकूलित प्रस्ताव प्राप्त करें',
    'financing.process.step3.number': '3',
    'financing.process.step3.title': 'ऋण के लिए आवेदन करें',
    'financing.process.step3.desc': 'हम दस्तावेज़ीकरण में मदद करते हैं',
    'financing.process.step4.number': '4',
    'financing.process.step4.title': 'स्थापना',
    'financing.process.step4.desc': 'त्वरित सेटअप और बचत शुरू करें',
    'financing.process.applyBtn': 'अभी आवेदन करें',
    'financing.process.subsidyBtn': 'सब्सिडी विवरण देखें',
    'financing.cta.title': 'सोलर को किफायती बनाने के लिए तैयार हैं?',


    // NotFound Page
    'notfound.title': '404',
    'notfound.message': 'क्षमा करें! पेज नहीं मिला',
    'notfound.home': 'होम पर वापस जाएं',

    // Notification Bar
    'notification.subsidy': 'रूफटॉप सोलर पर 60% तक सब्सिडी प्राप्त करें - अभी आवेदन करें',
    'notification.financing': 'आसान EMI विकल्प उपलब्ध - आज ही सोलर लगाएं',
    'notification.scheme': 'घर मालिकों के लिए सरकारी योजनाएं उपलब्ध - यहां क्लिक करें',

    // Subsidy Popup
    'popup.title': 'PM सोलर सब्सिडी उपलब्ध!',
    'popup.subtitle': 'अपने रूफटॉप सोलर इंस्टॉलेशन पर 60% तक सब्सिडी प्राप्त करें',
    'popup.benefits': 'लाभ में शामिल हैं:',
    'popup.point1': '3kW+ सिस्टम के लिए ₹1,08,000 तक सब्सिडी',
    'popup.point2': 'बिजली बिल में 90% तक की कमी',
    'popup.point3': 'आसान आवेदन के साथ सरकार समर्थित योजना',
    'popup.point4': 'आसान फाइनेंसिंग विकल्पों के साथ संयुक्त',
    'popup.cta1': 'पात्रता जांचें',
    'popup.cta2': 'फाइनेंसिंग देखें',
    'popup.note': 'सीमित समय का ऑफर • सरकार द्वारा अनुमोदित • त्वरित प्रसंस्करण',
    
    // Services Page
    'services.hero.badge': 'व्यापक सोलर सेवाएं',
    'services.hero.title': 'हर जरूरत के लिए',
    'services.hero.titleHighlight': 'सोलर समाधान',
    'services.hero.subtitle': 'रेजिडेंशियल रूफटॉप से लेकर बड़े कमर्शियल इंस्टॉलेशन तक, हम आपकी आवश्यकताओं के अनुरूप एंड-टू-एंड सोलर समाधान प्रदान करते हैं',
    'services.residential.title': 'रेजिडेंशियल सोलर समाधान',
    'services.residential.desc': 'अपने घर को हमारे कस्टमाइज़्ड रूफटॉप सोलर सिस्टम के साथ स्वच्छ ऊर्जा पावरहाउस में बदलें',
    'services.commercial.title': 'कमर्शियल और इंडस्ट्रियल सोलर',
    'services.commercial.desc': 'अपने व्यवसाय को लागत प्रभावी सोलर समाधानों के साथ बढ़ाएं जो परिचालन खर्चों को कम करते हैं',
    'services.maintenance.title': 'मेंटेनेंस और सपोर्ट',
    'services.maintenance.desc': 'हमारी व्यापक रखरखाव सेवाओं के साथ अपने सोलर सिस्टम को उच्चतम प्रदर्शन पर चलाते रहें',
    'services.process.title': 'हमारी स्थापना प्रक्रिया',
    'services.process.subtitle': 'सरल, पारदर्शी और परेशानी मुक्त',
    'services.process.step1': 'परामर्श',
    'services.process.step1.desc': 'मुफ्त साइट मूल्यांकन और सिस्टम डिज़ाइन',
    'services.process.step2': 'योजना',
    'services.process.step2.desc': 'वित्तपोषण, अनुमति और अनुमोदन',
    'services.process.step3': 'स्थापना',
    'services.process.step3.desc': 'प्रमाणित टीम द्वारा पेशेवर स्थापना',
    'services.process.step4': 'सहायता',
    'services.process.step4.desc': 'निगरानी, रखरखाव और निरंतर सहायता',
    'services.cta.title': 'आज ही अपनी सोलर यात्रा शुरू करें',
    'services.cta.subtitle': 'अपनी जरूरतों के लिए मुफ्त परामर्श और कस्टम सोलर समाधान प्राप्त करें',
    'services.residential.feature1': 'आपकी छत के लिए कस्टम डिज़ाइन',
    'services.residential.feature2': 'उच्च दक्षता सौर पैनल',
    'services.residential.feature3': '25 साल की प्रदर्शन वारंटी',
    'services.residential.feature4': 'नेट मीटरिंग सेटअप शामिल',
    'services.residential.feature5': 'PM सब्सिडी सहायता',
    'services.commercial.feature1': 'बड़े पैमाने पर इंस्टॉलेशन',
    'services.commercial.feature2': 'ऊर्जा लेखा परीक्षा और अनुकूलन',
    'services.commercial.feature3': 'त्वरित ROI (3-5 वर्ष)',
    'services.commercial.feature4': 'कर लाभ और मूल्यह्रास',
    'services.commercial.feature5': 'बिजली खरीद समझौते',
    'services.maintenance.feature1': '24/7 निगरानी प्रणाली',
    'services.maintenance.feature2': 'नियमित सफाई और निरीक्षण',
    'services.maintenance.feature3': 'प्रदर्शन अनुकूलन',
    'services.maintenance.feature4': 'त्वरित ब्रेकडाउन सपोर्ट',
    'services.maintenance.feature5': 'विस्तारित वारंटी विकल्प',
    
    // Residential Service
    'residential.hero.title': 'अपने घर को शक्ति दें',
    'residential.hero.titleHighlight': 'स्वच्छ ऊर्जा',
    'residential.hero.subtitle': 'हमारे प्रीमियम रूफटॉप सोलर सिस्टम के साथ बिजली बिल में 90% तक की बचत करें। स्थापना लागत पर 60% तक सरकारी सब्सिडी प्राप्त करें।',
    'residential.hero.cta1': 'मुफ्त मूल्यांकन पाएं',
    'residential.hero.cta2': 'सब्सिडी जांचें',
    'residential.features.title': 'आवासीय सौर ऊर्जा प्रणाली विशेषताएं',
    'residential.features.subtitle': 'आपके घर के लिए पूर्ण समाधान',
    'residential.features.feature1.title': 'आपकी छत के लिए कस्टम डिज़ाइन',
    'residential.features.feature1.desc': 'आपके घर के लिए विशेष रूप से डिज़ाइन की गई',
    'residential.features.feature2.title': 'उच्च दक्षता सौर पैनल',
    'residential.features.feature2.desc': '21%+ दक्षता वाले प्रीमियम पैनल',
    'residential.features.feature3.title': '25 साल की प्रदर्शन वारंटी',
    'residential.features.feature3.desc': 'लंबी अवधि की सुरक्षा और शांति',
    'residential.features.feature4.title': 'नेट मीटरिंग सेटअप शामिल',
    'residential.features.feature4.desc': 'पूर्ण स्थापना सेवा',
    'residential.features.feature5.title': 'PM सब्सिडी सहायता',
    'residential.features.feature5.desc': 'सरकारी लाभ प्राप्त करने में सहायता',
    'residential.benefits.title': 'अपने घर के लिए सोलर क्यों चुनें?',
    'residential.benefits.subtitle': 'कई लाभ जो सोलर को आपके घर के लिए स्मार्ट विकल्प बनाते हैं',
    'residential.benefits.benefit1.title': 'पैसे बचाएं',
    'residential.benefits.benefit1.desc': 'बिजली के बिल को 90% तक कम करें',
    'residential.benefits.benefit2.title': 'स्वच्छ ऊर्जा',
    'residential.benefits.benefit2.desc': 'शून्य उत्सर्जन, 100% नवीकरणीय ऊर्जा',
    'residential.benefits.benefit3.title': '25 साल की वारंटी',
    'residential.benefits.benefit3.desc': 'दीर्घकालिक प्रदर्शन गारंटी',
    'residential.benefits.benefit4.title': 'ऊर्जा स्वतंत्रता',
    'residential.benefits.benefit4.desc': 'अपनी बिजली खुद उत्पन्न करें',
    'residential.components.title': 'पूर्ण सोलर सिस्टम घटक',
    'residential.components.subtitle': 'प्रीमियम गुणवत्ता वाले घटक',
    'residential.components.panel.title': 'उच्च दक्षता सौर पैनल',
    'residential.components.panel.desc': '21%+ दक्षता के साथ मोनोक्रिस्टलाइन, पॉलीक्रिस्टलाइन और पतली फिल्म पैनल',
    'residential.components.inverter.title': 'स्मार्ट/हाइब्रिड इन्वर्टर',
    'residential.components.inverter.desc': 'बैटरी बैकअप क्षमता के साथ उन्नत बिजली प्रबंधन',
    'residential.components.monitoring.title': 'निगरानी प्रणाली',
    'residential.components.monitoring.desc': 'मोबाइल ऐप के माध्यम से रियल-टाइम ट्रैकिंग',
    'residential.components.structure.title': 'IIT अनुमोदित संरचनाएं',
    'residential.components.structure.desc': 'गर्म/ठंडे गैल्वनाइज्ड स्थिर माउंटिंग संरचनाएं',
    'residential.components.subsidy.title': 'सरकारी सब्सिडी',
    'residential.components.subsidy.desc': '₹1,08,000 तक की सरकारी सब्सिडी प्राप्त करें',
    'residential.pricing.title': 'सिस्टम आकार और निवेश',
    'residential.pricing.subtitle': 'अपने घर और बजट के लिए सही सिस्टम चुनें',
    'residential.pricing.ongrid': 'ऑन-ग्रिड सौर प्रणाली',
    'residential.pricing.hybrid': 'हाइब्रिड सौर प्रणाली (बैटरी बैकअप के साथ)',
    'residential.pricing.systemSize': 'प्रणाली का आकार',
    'residential.pricing.suitable': 'उपयुक्त:',
    'residential.pricing.generation': 'उत्पादन:',
    'residential.pricing.investment': 'निवेश:',
    'residential.pricing.subsidy': 'PM सब्सिडी:',
    'residential.pricing.payback': 'वापसी:',
    'residential.pricing.unitsPerDay': 'यूनिट/दिन',
    'residential.pricing.years': 'वर्ष',
    'residential.pricing.quote': 'विस्तृत उद्धरण प्राप्त करें',
    'residential.pricing.bhk2_3': '2-3 BHK',
    'residential.pricing.bhk3_4': '3-4 BHK',
    'residential.pricing.largeHomes': 'बड़े घर',
    'residential.process.title': 'सरल स्थापना प्रक्रिया',
    'residential.process.subtitle': 'परामर्श से लेकर कमीशनिंग तक, हम सब कुछ संभालते हैं',
    'residential.process.step1.title': 'साइट विजिट',
    'residential.process.step1.desc': 'मुफ्त छत मूल्यांकन और छाया विश्लेषण',
    'residential.process.step2.title': 'डिज़ाइन',
    'residential.process.step2.desc': 'कस्टम सिस्टम डिज़ाइन और सब्सिडी आवेदन',
    'residential.process.step3.title': 'स्थापना',
    'residential.process.step3.desc': '2-3 दिनों में पेशेवर स्थापना',
    'residential.process.step4.title': 'सक्रिय करें',
    'residential.process.step4.desc': 'नेट मीटरिंग और सिस्टम कमीशनिंग',
    'residential.comparison.title': 'सिस्टम तुलना',
    'residential.comparison.ongrid.title': 'ऑन-ग्रिड सिस्टम',
    'residential.comparison.ongrid.desc': 'कोई बैटरी नहीं, केवल ग्रिड से जुड़ा। कम लागत लेकिन बिजली कटौती के दौरान कोई बैकअप नहीं।',
    'residential.comparison.hybrid.title': 'हाइब्रिड सिस्टम ⭐',
    'residential.comparison.hybrid.desc': 'दोनों का सर्वश्रेष्ठ - ग्रिड + बैटरी बैकअप। बिजली कटौती के दौरान बिजली + नेट मीटरिंग लाभ।',
    'residential.comparison.offgrid.title': 'ऑफ-ग्रिड सिस्टम',
    'residential.comparison.offgrid.desc': 'बैटरी के साथ पूर्ण स्वतंत्रता। अधिक लागत, नेट मीटरिंग लाभ नहीं।',
    'residential.cta.title': 'अपने घर को सोलर से शक्ति देने के लिए तैयार हैं?',
    'residential.cta.subtitle': 'मुफ्त साइट मूल्यांकन और व्यक्तिगत सोलर समाधान के साथ शुरुआत करें',
    'residential.cta.btn': 'मुफ्त साइट विजिट शेड्यूल करें',
    
    // Commercial Service
    'commercial.hero.badge': 'एंटरप्राइज़ सोलर समाधान',
    'commercial.hero.title': 'अपने व्यवसाय को बदलें',
    'commercial.hero.titleHighlight': 'सोलर पावर',
    'commercial.hero.subtitle': 'स्केलेबल कमर्शियल सोलर समाधानों के साथ परिचालन लागत में 80% तक की कमी। टैक्स लाभ और त्वरित मूल्यह्रास के साथ 3-4 वर्षों में ROI।',
    'commercial.features.title': 'व्यावसायिक सौर ऊर्जा विशेषताएं',
    'commercial.features.subtitle': 'हर व्यवसाय के लिए पूर्ण समाधान',
    'commercial.features.feature1.title': 'बड़े पैमाने पर स्थापना',
    'commercial.features.feature1.desc': 'औद्योगिक और वाणिज्यिक परियोजनाओं के लिए',
    'commercial.features.feature2.title': 'ऊर्जा ऑडिट और अनुकूलन',
    'commercial.features.feature2.desc': 'विस्तृत खपत विश्लेषण',
    'commercial.features.feature3.title': 'त्वरित ROI (3-5 वर्ष)',
    'commercial.features.feature3.desc': 'तेजी से निवेश वापसी',
    'commercial.features.feature4.title': 'कर लाभ और मूल्यह्रास',
    'commercial.features.feature4.desc': '40% त्वरित मूल्यह्रास लाभ',
    'commercial.features.feature5.title': 'बिजली खरीद समझौते',
    'commercial.features.feature5.desc': 'लचीले वित्तीय विकल्प',
    'commercial.why.title': 'व्यवसाय सौर ऊर्जा क्यों चुनते हैं',
    'commercial.why.subtitle': 'स्वच्छ ऊर्जा के साथ अपनी बॉटम लाइन को बदलें',
    'commercial.why.benefit1.title': 'परिचालन लागत कम करें',
    'commercial.why.benefit1.desc': '25+ वर्षों के लिए लॉक-इन ऊर्जा दरों के साथ बिजली के बिल पर 70-80% बचाएं',
    'commercial.why.benefit1.stat': '₹20L+ वार्षिक बचत',
    'commercial.why.benefit2.title': 'त्वरित ROI और कर लाभ',
    'commercial.why.benefit2.desc': 'पहले वर्ष में 40% त्वरित मूल्यह्रास के साथ 3-5 वर्षों में वापसी',
    'commercial.why.benefit2.stat': '40% कर लाभ',
    'commercial.why.benefit3.title': 'कॉर्पोरेट स्थिरता',
    'commercial.why.benefit3.desc': 'ESG लक्ष्यों को पूरा करें, कार्बन फुटप्रिंट कम करें, और ब्रांड प्रतिष्ठा बढ़ाएं',
    'commercial.why.benefit3.stat': '100% हरित ऊर्जा',
    'commercial.benefits.title': 'कमर्शियल सोलर क्यों',
    'commercial.industries.title': 'उद्योग-विशिष्ट समाधान',
    'commercial.industries.subtitle': 'हर व्यवसाय प्रकार के लिए अनुकूलित सौर प्रणाली',
    'commercial.industries.manufacturing.title': 'विनिर्माण',
    'commercial.industries.manufacturing.desc': 'दिन के समय उच्च खपत के साथ भारी बिजली उपयोगकर्ता',
    'commercial.industries.warehouses.title': 'गोदाम',
    'commercial.industries.warehouses.desc': 'अधिकतम उत्पादन के लिए बड़ी छत स्थान',
    'commercial.industries.hotels.title': 'होटल और रिसॉर्ट',
    'commercial.industries.hotels.desc': 'लगातार ऊर्जा जरूरतों के साथ 24/7 संचालन',
    'commercial.industries.offices.title': 'IT पार्क और कार्यालय',
    'commercial.industries.offices.desc': 'व्यावसायिक घंटों के दौरान पीक लोड',
    'commercial.systems.title': 'सिस्टम आकार और कॉन्फ़िगरेशन',
    'commercial.packages.title': 'स्केलेबल सौर समाधान',
    'commercial.packages.subtitle': 'छोटे कार्यालयों से बड़ी औद्योगिक सुविधाओं तक, हम आपकी ऊर्जा जरूरतों और बजट से मेल खाने वाली प्रणाली डिज़ाइन करते हैं।',
    'commercial.packages.small.title': 'छोटे वाणिज्यिक',
    'commercial.packages.small.size': '25-50 kW',
    'commercial.packages.small.cost': '₹12-25 लाख',
    'commercial.packages.small.generation': '150-200 यूनिट/दिन',
    'commercial.packages.medium.title': 'मध्यम वाणिज्यिक',
    'commercial.packages.medium.size': '50-100 kW',
    'commercial.packages.medium.cost': '₹25-50 लाख',
    'commercial.packages.medium.generation': '200-400 यूनिट/दिन',
    'commercial.packages.large.title': 'बड़े औद्योगिक',
    'commercial.packages.large.size': '100-500 kW',
    'commercial.packages.large.cost': '₹50L-2.5 करोड़',
    'commercial.packages.large.generation': '400-2000 यूनिट/दिन',
    'commercial.packages.mega.title': 'मेगा परियोजनाएं',
    'commercial.packages.mega.size': '500 kW+',
    'commercial.packages.mega.cost': 'कस्टम उद्धरण',
    'commercial.packages.mega.generation': '2000+ यूनिट/दिन',
    'commercial.packages.dailyGen': 'दैनिक उत्पादन:',
    'commercial.packages.customBtn': 'कस्टम साइजिंग प्राप्त करें',
    'commercial.package.title': 'पूर्ण कमर्शियल पैकेज',
    'commercial.complete.title': 'पूर्ण वाणिज्यिक पैकेज',
    'commercial.complete.subtitle': 'सफल सौर कार्यान्वयन के लिए आपको जो कुछ भी चाहिए',
    'commercial.complete.audit.title': 'ऊर्जा ऑडिट',
    'commercial.complete.audit.desc': 'विस्तृत खपत विश्लेषण और सिस्टम साइजिंग',
    'commercial.complete.design.title': 'कस्टम डिज़ाइन',
    'commercial.complete.design.desc': 'आपकी छत संरचना और ऊर्जा जरूरतों के अनुसार',
    'commercial.complete.quality.title': 'गुणवत्ता आश्वासन',
    'commercial.complete.quality.desc': 'टियर-1 प्रमाणपत्र के साथ प्रीमियम घटक',
    'commercial.complete.grid.title': 'ग्रिड एकीकरण',
    'commercial.complete.grid.desc': 'मौजूदा बिजली आपूर्ति के साथ सहज कनेक्शन',
    'commercial.complete.monitoring.title': 'प्रदर्शन निगरानी',
    'commercial.complete.monitoring.desc': 'रियल-टाइम ट्रैकिंग और अनुकूलन',
    'commercial.complete.support.title': 'O&M सहायता',
    'commercial.complete.support.desc': '25+ वर्षों के लिए व्यापक रखरखाव',
    'commercial.cta.title': 'चलिए अपना सौर समाधान बनाएं',
    'commercial.cta.subtitle': 'मुफ्त ऊर्जा ऑडिट शेड्यूल करें और जानें कि आप कितना बचा सकते हैं',
    'commercial.cta.btn': 'ऊर्जा ऑडिट का अनुरोध करें',
    'commercial.cta.financingBtn': 'वित्तपोषण विकल्प देखें',
    
    // Products Page
    'products.hero.title': 'उच्च-प्रदर्शन',
    'products.hero.titleHighlight': 'सोलर प्रौद्योगिकी',
    'products.hero.subtitle': 'हम भारत में सबसे कुशल और विश्वसनीय सोलर उत्पाद लाने के लिए विश्व स्तरीय निर्माताओं के साथ साझेदारी करते हैं।',
    'products.hero.badge': 'प्रीमियम सोलर उत्पाद',
    'products.panels.title': 'मोनोक्रिस्टलाइन सोलर पैनल',
    'products.panels.desc': 'प्रीमियम मोनोक्रिस्टलाइन तकनीक के साथ उद्योग-अग्रणी दक्षता। हमारे पैनल कम रोशनी की स्थिति में भी अधिकतम बिजली उत्पादन प्रदान करते हैं।',
    'products.panels.feature1': '21%+ मॉड्यूल दक्षता',
    'products.panels.feature2': '540-550W उच्च-शक्ति मॉड्यूल',
    'products.panels.feature3': '25-वर्ष रैखिक प्रदर्शन वारंटी',
    'products.panels.feature4': 'IEC/CE/ISO प्रमाणित',
    'products.panels.feature5': 'PID और LID प्रतिरोधी तकनीक',
    'products.panels.feature6': '2400 Pa तक बर्फ भार सहन करता है',
    'products.panels.stat1.value': '25+',
    'products.panels.stat1.label': 'वर्ष जीवनकाल',
    'products.panels.stat2.value': '21%',
    'products.panels.stat2.label': 'दक्षता',
    'products.panels.stat3.value': '550W',
    'products.panels.stat3.label': 'अधिकतम पावर',
    'products.inverters.title': 'स्मार्ट सोलर इन्वर्टर',
    'products.inverters.desc': 'अधिकतम दक्षता के साथ DC को AC पावर में बदलें। हमारे स्मार्ट और हाइब्रिड इन्वर्टर उन्नत निगरानी, बैटरी प्रबंधन और सुरक्षा सुविधाओं के साथ आते हैं।',
    'products.inverters.type1.title': 'ऑन-ग्रिड इन्वर्टर',
    'products.inverters.type1.desc': 'नेट मीटरिंग के साथ ग्रिड-टाइड सिस्टम',
    'products.inverters.type2.title': 'हाइब्रिड इन्वर्टर',
    'products.inverters.type2.desc': 'ग्रिड कनेक्टिविटी के साथ स्मार्ट बैटरी बैकअप',
    'products.inverters.type3.title': 'ऑफ-ग्रिड इन्वर्टर',
    'products.inverters.type3.desc': 'पूर्ण ऊर्जा स्वतंत्रता',
    'products.inverters.type4.title': 'माइक्रो इन्वर्टर',
    'products.inverters.type4.desc': 'पैनल-स्तरीय अनुकूलन',
    'products.inverters.feature1': 'स्मार्ट और हाइब्रिड इन्वर्टर तकनीक',
    'products.inverters.feature2': '98%+ रूपांतरण दक्षता',
    'products.inverters.feature3': 'WiFi और मोबाइल ऐप निगरानी',
    'products.inverters.feature4': 'बैटरी प्रबंधन प्रणाली',
    'products.inverters.feature5': '5-10 वर्ष वारंटी',
    'products.inverters.feature6': 'ओवरलोड और शॉर्ट सर्किट सुरक्षा',
    'products.storage.title': 'ऊर्जा भंडारण समाधान',
    'products.storage.subtitle': 'दिन या रात किसी भी समय उपयोग के लिए सौर ऊर्जा स्टोर करें',
    'products.storage.battery1.title': 'लिथियम-आयन बैटरी',
    'products.storage.battery1.capacity': '5-15 kWh',
    'products.storage.battery1.cycles': '6000+ चक्र',
    'products.storage.battery1.warranty': '10 वर्ष',
    'products.storage.battery1.feature1': 'स्मार्ट BMS',
    'products.storage.battery1.feature2': 'तेज चार्जिंग',
    'products.storage.battery1.feature3': '80% DoD',
    'products.storage.battery1.feature4': 'कॉम्पैक्ट डिज़ाइन',
    'products.storage.battery2.title': 'लेड-एसिड बैटरी',
    'products.storage.battery2.capacity': '150-250 Ah',
    'products.storage.battery2.cycles': '1500+ चक्र',
    'products.storage.battery2.warranty': '5 वर्ष',
    'products.storage.battery2.feature1': 'लागत प्रभावी',
    'products.storage.battery2.feature2': 'सिद्ध प्रौद्योगिकी',
    'products.storage.battery2.feature3': 'आसान रखरखाव',
    'products.storage.battery2.feature4': 'व्यापक उपलब्धता',
    'products.storage.battery3.title': 'बैटरी प्रबंधन',
    'products.storage.battery3.capacity': 'स्मार्ट नियंत्रण',
    'products.storage.battery3.cycles': 'अनुकूलित',
    'products.storage.battery3.warranty': 'सुरक्षित',
    'products.storage.battery3.feature1': 'रियल-टाइम निगरानी',
    'products.storage.battery3.feature2': 'ऑटो सुरक्षा',
    'products.storage.battery3.feature3': 'तापमान नियंत्रण',
    'products.storage.battery3.feature4': 'चार्ज अनुकूलन',
    'products.storage.capacity': 'क्षमता:',
    'products.storage.cycles': 'जीवन चक्र:',
    'products.storage.warranty': 'वारंटी:',
    'products.certifications.title': 'गुणवत्ता प्रमाणपत्र',
    'products.certifications.subtitle': 'सभी उत्पाद अंतरराष्ट्रीय गुणवत्ता मानकों को पूरा करते हैं',
    'products.certifications.cert1.title': 'IEC प्रमाणित',
    'products.certifications.cert1.desc': 'अंतरराष्ट्रीय मानक',
    'products.certifications.cert2.title': 'ISO प्रमाणित',
    'products.certifications.cert2.desc': 'गुणवत्ता प्रबंधन',
    'products.certifications.cert3.title': 'CE चिह्नित',
    'products.certifications.cert3.desc': 'यूरोपीय अनुरूपता',
    'products.certifications.cert4.title': 'MNRE अनुमोदित',
    'products.certifications.cert4.desc': 'सरकार द्वारा मान्यता प्राप्त',
    'products.cta.title': 'विशेषज्ञ उत्पाद सिफारिशें प्राप्त करें',
    'products.cta.subtitle': 'अपनी आवश्यकताओं के लिए सही सोलर उत्पाद चुनने के लिए हमारे तकनीकी विशेषज्ञों से बात करें',
    'products.cta.btn': 'हमारे विशेषज्ञों से परामर्श लें',
    
    // PM Subsidy Page
    'subsidy.hero.title': 'PM सोलर रूफटॉप',
    'subsidy.hero.titleHighlight': 'सब्सिडी योजना',
    'subsidy.hero.subtitle': 'अपने रूफटॉप सोलर इंस्टॉलेशन पर ₹108,000 तक सब्सिडी प्राप्त करें।',
    'subsidy.hero.desc': 'सरकारी सहायता के साथ हर भारतीय परिवार के लिए सोलर को किफायती और सुलभ बनाएं।',
    'subsidy.hero.cta1': 'सब्सिडी के लिए आवेदन करें',
    'subsidy.hero.cta2': 'वित्तपोषण विकल्प देखें',
    'subsidy.hero.badge': 'सरकार द्वारा अनुमोदित • 60% तक सब्सिडी',
    'subsidy.hero.stat1': 'सब्सिडी',
    'subsidy.hero.stat2': 'अधिकतम राशि',
    'subsidy.benefits.title': 'सब्सिडी लाभ',
    'subsidy.benefits.subtitle': 'PM सोलर रूफटॉप योजना सौर ऊर्जा को किफायती बनाने के लिए पर्याप्त वित्तीय सहायता प्रदान करती है',
    'subsidy.benefits.card1.title': '₹1,08,000 तक सब्सिडी',
    'subsidy.benefits.card1.desc': '3kW+ सिस्टम के लिए - आवासीय क्षेत्र को अधिकतम लाभ मिलता है',
    'subsidy.benefits.card2.title': '60% लागत में कमी',
    'subsidy.benefits.card2.desc': 'सब्सिडी आपकी कुल स्थापना लागत का 60% तक कवर करती है',
    'subsidy.benefits.card3.title': 'पूरे भारत में कवरेज',
    'subsidy.benefits.card3.desc': 'सभी राज्यों में आवासीय उपभोक्ताओं के लिए उपलब्ध',
    'subsidy.table.title': 'सिस्टम क्षमता के अनुसार सब्सिडी विवरण',
    'subsidy.table.capacity': 'सिस्टम क्षमता',
    'subsidy.table.rate': 'सब्सिडी दर',
    'subsidy.table.max': 'अधिकतम सब्सिडी',
    'subsidy.table.investment': 'आपका निवेश',
    'subsidy.table.popular': 'सबसे लोकप्रिय',
    'subsidy.table.note': 'स्थापना और निरीक्षण के बाद सब्सिडी सीधे आपके खाते में जमा की जाती है। दिखाई गई लागत अनुमानित है और स्थान और सिस्टम विनिर्देशों के आधार पर भिन्न हो सकती है।',
    'subsidy.eligibility.title': 'पात्रता',
    'subsidy.eligibility.titleHighlight': 'मानदंड',
    'subsidy.eligibility.whocan.title': 'कौन आवेदन कर सकता है?',
    'subsidy.eligibility.whocan.point1': 'व्यक्तिगत घर के मालिक',
    'subsidy.eligibility.whocan.point2': 'आवासीय कल्याण संघ',
    'subsidy.eligibility.whocan.point3': 'सामूहिक आवास सोसायटी',
    'subsidy.eligibility.whocan.point4': 'भारत में सभी आवासीय उपभोक्ता',
    'subsidy.eligibility.docs.title': 'आवश्यक दस्तावेज़',
    'subsidy.eligibility.docs.point1': 'बिजली बिल की प्रति',
    'subsidy.eligibility.docs.point2': 'आधार कार्ड',
    'subsidy.eligibility.docs.point3': 'पैन कार्ड',
    'subsidy.eligibility.docs.point4': 'बैंक खाता विवरण',
    'subsidy.eligibility.docs.point5': 'संपत्ति स्वामित्व प्रमाण',
    'subsidy.apply.title': 'आवेदन कैसे',
    'subsidy.apply.titleHighlight': 'करें',
    'subsidy.apply.subtitle': 'अपनी सोलर सब्सिडी को स्वीकृत करने के लिए सरल 5-चरण प्रक्रिया',
    'subsidy.apply.step1.title': 'रजिस्टर करें',
    'subsidy.apply.step1.desc': 'राष्ट्रीय पोर्टल पर रजिस्टर करें',
    'subsidy.apply.step2.title': 'विक्रेता चुनें',
    'subsidy.apply.step2.desc': 'अपने इंस्टॉलर के रूप में ATP इंफ्राटेक चुनें',
    'subsidy.apply.step3.title': 'सिस्टम स्थापित करें',
    'subsidy.apply.step3.desc': 'हम आपका सोलर सिस्टम स्थापित करते हैं',
    'subsidy.apply.step4.title': 'निरीक्षण',
    'subsidy.apply.step4.desc': 'डिस्कॉम निरीक्षण और नेट मीटरिंग',
    'subsidy.apply.step5.title': 'सब्सिडी प्राप्त करें',
    'subsidy.apply.step5.desc': 'सब्सिडी आपके खाते में जमा की गई',
    'subsidy.apply.cta': 'अपना आवेदन शुरू करें',
    'subsidy.apply.note': 'हम पूरी प्रक्रिया में आपका मार्गदर्शन करेंगे',
    'subsidy.combine.title': 'सब्सिडी को फाइनेंसिंग के साथ मिलाएं',
    'subsidy.combine.subtitle': 'दोनों का सर्वोत्तम लाभ प्राप्त करें - 60% सब्सिडी + आसान EMI विकल्प',
    'subsidy.combine.cta1': 'वित्तपोषण विकल्प देखें',
    'subsidy.combine.cta2': 'विशेषज्ञ परामर्श प्राप्त करें',
    
    // Maintenance Page
    'maintenance.hero.badge': 'प्रोफेशनल केयर • 24/7 सपोर्ट',
    'maintenance.hero.title': 'मेंटेनेंस और',
    'maintenance.hero.subtitle': 'सपोर्ट सेवाएं',
    'maintenance.hero.desc': 'हमारी व्यापक रखरखाव और रियल-टाइम निगरानी सेवाओं के साथ अपने सोलर सिस्टम को उच्चतम प्रदर्शन पर चलाते रहें।',
    'maintenance.why.title': 'नियमित रखरखाव क्यों महत्वपूर्ण है',
    'maintenance.why.titleHighlight': 'रखरखाव',
    'maintenance.why.titleEnd': 'महत्वपूर्ण है',
    'maintenance.why.subtitle': 'उचित रखरखाव अधिकतम ऊर्जा उत्पादन सुनिश्चित करता है और सिस्टम जीवनकाल बढ़ाता है',
    'maintenance.why.output.title': '20-30% अधिक उत्पादन',
    'maintenance.why.output.desc': 'स्वच्छ पैनल गंदे पैनलों की तुलना में काफी अधिक बिजली उत्पन्न करते हैं',
    'maintenance.why.lifespan.title': 'विस्तारित जीवनकाल',
    'maintenance.why.lifespan.desc': 'नियमित रखरखाव सिस्टम जीवन को 25 से 30+ वर्ष तक बढ़ा सकता है',
    'maintenance.why.downtime.title': 'डाउनटाइम रोकें',
    'maintenance.why.downtime.desc': 'मुद्दों का जल्द पता लगाने से महंगी मरम्मत और ऊर्जा हानि रुकती है',
    'maintenance.services.title': 'हमारी रखरखाव सेवाएं',
    'maintenance.services.titleHighlight': 'रखरखाव सेवाएं',
    'maintenance.services.cleaning.title': 'पैनल सफाई सेवा',
    'maintenance.services.cleaning.desc': 'दक्षता कम करने वाली धूल, पक्षी की बीट और मलबे को हटाने के लिए पेशेवर सफाई।',
    'maintenance.services.cleaning.feat1': 'जलरहित या जल-आधारित सफाई विधियां',
    'maintenance.services.cleaning.feat2': 'सुरक्षित सफाई एजेंट जो पैनलों को नुकसान नहीं पहुंचाते',
    'maintenance.services.cleaning.feat3': 'त्रैमासिक सफाई अनुसूची अनुशंसित',
    'maintenance.services.cleaning.feat4': 'पहले/बाद उत्पादन तुलना रिपोर्ट',
    'maintenance.services.cleaning.price': '₹2/वाट से शुरू',
    'maintenance.services.monitoring.title': '24/7 निगरानी प्रणाली',
    'maintenance.services.monitoring.desc': 'प्रदर्शन ट्रैक करने और तुरंत मुद्दों का पता लगाने के लिए रियल-टाइम निगरानी।',
    'maintenance.services.monitoring.feat1': 'क्लाउड-आधारित निगरानी प्लेटफॉर्म',
    'maintenance.services.monitoring.feat2': 'रियल-टाइम डेटा के लिए मोबाइल ऐप एक्सेस',
    'maintenance.services.monitoring.feat3': 'सिस्टम विफलताओं के लिए तत्काल अलर्ट',
    'maintenance.services.monitoring.feat4': 'दैनिक, साप्ताहिक और मासिक रिपोर्ट',
    'maintenance.services.monitoring.price': 'कस्टम निगरानी शुल्क',
    'maintenance.services.checkup.title': 'नियमित जांच',
    'maintenance.services.checkup.desc': 'इष्टतम प्रदर्शन सुनिश्चित करने के लिए व्यापक सिस्टम निरीक्षण।',
    'maintenance.services.checkup.feat1': 'इन्वर्टर स्वास्थ्य और प्रदर्शन जांच',
    'maintenance.services.checkup.feat2': 'विद्युत कनेक्शन निरीक्षण',
    'maintenance.services.checkup.feat3': 'माउंटिंग संरचना स्थिरता जांच',
    'maintenance.services.checkup.feat4': 'थर्मल इमेजिंग का उपयोग करके पैनल हॉटस्पॉट का पता लगाना',
    'maintenance.services.checkup.price': 'अर्ध-वार्षिक निरीक्षण: ₹3,000/विजिट',
    'maintenance.services.repair.title': 'समस्या निवारण और मरम्मत',
    'maintenance.services.repair.desc': 'विशेषज्ञ तकनीकी सहायता के साथ सिस्टम मुद्दों पर त्वरित प्रतिक्रिया।',
    'maintenance.services.repair.feat1': '24 घंटे आपातकालीन प्रतिक्रिया',
    'maintenance.services.repair.feat2': 'इन्वर्टर प्रतिस्थापन और मरम्मत',
    'maintenance.services.repair.feat3': 'पैनल प्रतिस्थापन (यदि वारंटी के तहत)',
    'maintenance.services.repair.feat4': 'वायरिंग और कनेक्शन फिक्स',
    'maintenance.services.repair.price': 'मुद्दे के आधार पर ऑन-डिमांड मूल्य निर्धारण',
    'maintenance.amc.title': 'वार्षिक रखरखाव पैकेज',
    'maintenance.amc.titleHighlight': 'रखरखाव पैकेज',
    'maintenance.amc.subtitle': 'एक व्यापक पैकेज चुनें और रखरखाव लागत पर 30% तक बचाएं',
    'maintenance.packages.basic.title': 'बेसिक',
    'maintenance.packages.basic.price': '₹4,999/वर्ष',
    'maintenance.packages.basic.desc': 'छोटी प्रणालियों के लिए एकदम सही (3kW तक)',
    'maintenance.packages.basic.feat1': '2 सफाई सत्र/वर्ष',
    'maintenance.packages.basic.feat2': '1 सिस्टम निरीक्षण',
    'maintenance.packages.basic.feat3': 'ईमेल प्रदर्शन रिपोर्ट',
    'maintenance.packages.basic.feat4': 'फोन सहायता',
    'maintenance.packages.basic.btn': 'योजना चुनें',
    'maintenance.packages.standard.title': 'स्टैंडर्ड',
    'maintenance.packages.standard.badge': 'सबसे लोकप्रिय',
    'maintenance.packages.standard.price': '₹7,999/वर्ष',
    'maintenance.packages.standard.desc': '3-5kW प्रणालियों के लिए सर्वोत्तम मूल्य',
    'maintenance.packages.standard.feat1': '4 सफाई सत्र/वर्ष',
    'maintenance.packages.standard.feat2': '2 व्यापक निरीक्षण',
    'maintenance.packages.standard.feat3': '24/7 निगरानी शामिल',
    'maintenance.packages.standard.feat4': 'प्राथमिकता सहायता',
    'maintenance.packages.standard.feat5': 'मरम्मत पर 20% छूट',
    'maintenance.packages.standard.btn': 'योजना चुनें',
    'maintenance.packages.premium.title': 'प्रीमियम',
    'maintenance.packages.premium.price': '₹12,999/वर्ष',
    'maintenance.packages.premium.desc': '5kW+ प्रणालियों के लिए पूर्ण देखभाल',
    'maintenance.packages.premium.feat1': '6 सफाई सत्र/वर्ष',
    'maintenance.packages.premium.feat2': '4 व्यापक निरीक्षण',
    'maintenance.packages.premium.feat3': '24/7 निगरानी + अलर्ट',
    'maintenance.packages.premium.feat4': 'VIP सहायता (2 घंटे प्रतिक्रिया)',
    'maintenance.packages.premium.feat5': 'मरम्मत पर 30% छूट',
    'maintenance.packages.premium.feat6': 'मुफ्त थर्मल इमेजिंग जांच',
    'maintenance.packages.premium.btn': 'योजना चुनें',
    'maintenance.cta.title': 'आज अपना रखरखाव शेड्यूल करें',
    'maintenance.cta.subtitle': 'हमारी पेशेवर रखरखाव सेवाओं के साथ अपनी सौर प्रणाली को सर्वश्रेष्ठ प्रदर्शन पर रखें',
    'maintenance.cta.btn': 'रखरखाव का अनुरोध करें',
    'maintenance.cta.phone': '+91 73806 07555 पर कॉल करें',
    
    // Hybrid Solar
    'hybrid.title': 'हाइब्रिड सोलर सिस्टम',
    'hybrid.subtitle': 'दोनों का सर्वश्रेष्ठ - बैटरी बैकअप के साथ ग्रिड कनेक्टिविटी',
    'hybrid.desc': 'हाइब्रिड सोलर सिस्टम ऑन-ग्रिड और ऑफ-ग्रिड सिस्टम के लाभों को जोड़ते हैं, आपको ग्रिड कनेक्टिविटी के साथ-साथ बिजली कटौती के लिए बैटरी बैकअप प्रदान करते हैं।',
    'hybrid.benefit1': 'दिन में सोलर का उपयोग करें, रात में ग्रिड का',
    'hybrid.benefit2': 'बिजली कटौती के दौरान बैटरी बैकअप',
    'hybrid.benefit3': 'अतिरिक्त बिजली के लिए नेट मीटरिंग',
    'hybrid.benefit4': 'स्मार्ट पावर प्रबंधन',
    'hybrid.benefit5': 'ग्रिड पर निर्भरता कम करें',
    'hybrid.benefit6': 'कम बिजली बिल',

    // Solar Calculator Page
    'calculator.hero.badge': 'मुफ्त सोलर कैलकुलेटर',
    'calculator.hero.title': 'अपनी',
    'calculator.hero.titleHighlight': 'सोलर बचत की गणना करें',
    'calculator.hero.subtitle': 'जानें कि आप सोलर ऊर्जा से कितनी बचत कर सकते हैं। सिस्टम आकार, लागत और पेबैक अवधि का तुरंत अनुमान प्राप्त करें।',
    'calculator.form.title': 'अपना विवरण दर्ज करें',
    'calculator.form.monthlyBill': 'मासिक बिजली बिल (₹)',
    'calculator.form.roofArea': 'उपलब्ध छत क्षेत्र (वर्ग फुट)',
    'calculator.form.location': 'आपका स्थान',
    'calculator.form.systemType': 'सिस्टम प्रकार',
    'calculator.form.systemType.onGrid': 'ऑन-ग्रिड (बिना बैटरी)',
    'calculator.form.systemType.hybrid': 'हाइब्रिड (बैटरी के साथ)',
    'calculator.form.systemType.offGrid': 'ऑफ-ग्रिड (पूर्ण बैकअप)',
    'calculator.form.calculate': 'बचत की गणना करें',
    'calculator.results.title': 'आपकी सोलर बचत रिपोर्ट',
    'calculator.results.systemSize': 'अनुशंसित सिस्टम आकार',
    'calculator.results.totalCost': 'कुल सिस्टम लागत',
    'calculator.results.subsidy': 'सरकारी सब्सिडी',
    'calculator.results.finalCost': 'आपका अंतिम निवेश',
    'calculator.results.monthlySavings': 'मासिक बचत',
    'calculator.results.yearlySavings': 'वार्षिक बचत',
    'calculator.results.payback': 'पेबैक अवधि',
    'calculator.results.lifetimeSavings': '25-वर्ष की बचत',
    'calculator.results.co2Reduction': 'CO₂ में कमी',
    'calculator.benefits.title': 'आपके लाभ में शामिल हैं',
    'calculator.benefits.point1': 'बिजली बिल में 90% तक की कमी',
    'calculator.benefits.point2': 'सिस्टम लागत पर 60% सरकारी सब्सिडी',
    'calculator.benefits.point3': '25 साल की प्रदर्शन वारंटी',
    'calculator.benefits.point4': 'संपत्ति मूल्य में 3-4% की वृद्धि',
    'calculator.benefits.point5': '5+ वर्षों के लिए शून्य रखरखाव',
    'calculator.benefits.point6': '24/7 निगरानी और सहायता',
    'calculator.cta.title': 'सोलर के लिए तैयार हैं?',
    'calculator.cta.subtitle': 'हमारे विशेषज्ञों से विस्तृत कोटेशन प्राप्त करें',
    'calculator.cta.button': 'मुफ्त परामर्श प्राप्त करें',
  },
};
